/**
 * 男友相机 - getTemplates 云函数 v35
 * 385 个姿势模板，覆盖室内/户外/餐厅/特殊风格/情侣合照/城市街拍等全场景
 * 模板涵盖：日常自拍、约会合照、户外风景、美食餐厅、城市街拍、节日庆典等
 */

const CURRENT_VERSION = 36

// ===== Deterministic SVG generator (replaces 170 static constants, reduces ~60KB) =====
function genSVG(id) {
  let s = (id * 2654435761) >>> 0
  const rng = () => { s = Math.imul(s ^ (s >>> 16), 0x45d9f3b) >>> 0; return (s >>> 0) / 0xFFFFFFFF }
  const n = () => Math.floor(rng() * 280) + 10
  const rgba = () => `rgba(${Math.floor(rng()*90+165)},${Math.floor(rng()*90+165)},${Math.floor(rng()*90+165)},${(rng()*0.3+0.15).toFixed(2)})`
  const f = rgba()
  const els = [
    `<ellipse cx="${n()}" cy="${n()}" rx="${n()}" ry="${n()}" fill="${rgba()}"/>`,
    `<ellipse cx="${n()}" cy="${n()}" rx="${n()}" ry="${n()}" fill="${rgba()}"/>`,
    `<ellipse cx="${n()}" cy="${n()}" rx="${n()}" ry="${n()}" fill="${rgba()}"/>`,
    `<ellipse cx="${n()}" cy="${n()}" rx="${n()}" ry="${n()}" fill="${rgba()}"/>`,
    `<rect x="${n()}" y="${n()}" width="${n()}" height="${n()}" fill="${rgba()}"/>`,
    `<rect x="${n()}" y="${n()}" width="${n()}" height="${n()}" fill="${rgba()}"/>`,
    `<circle cx="${n()}" cy="${n()}" r="${Math.floor(rng()*12+4)}" fill="${rgba()}"/>`,
    `<circle cx="${n()}" cy="${n()}" r="${Math.floor(rng()*12+4)}" fill="${rgba()}"/>`,
    `<circle cx="${n()}" cy="${n()}" r="${Math.floor(rng()*12+4)}" fill="${rgba()}"/>`,
    `<ellipse cx="${n()}" cy="${n()}" rx="${n()}" ry="${n()}" fill="${rgba()}"/>`,
  ]
  return `data:image/svg+xml;base64,${Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 300" fill="'+f+'" stroke="rgba(255,255,255,0.6)" stroke-width="1.5">'+els.join('')+'</svg>').toString('base64')}`
}

const ALL_TEMPLATES = [
  {
    id: "template_001",
    description: "微微侧身，回头看镜头，自然又显瘦",
    overlayUrl: genSVG(001),
    thumbnail: genSVG(001),
    voiceTip: "侧身站好，轻轻回头看我，笑一个～",
    category: "室内日常",
    version: 5,
  },
  {
    id: "template_002",
    description: "一只手轻轻撩起头发，优雅又灵动",
    overlayUrl: genSVG(002),
    thumbnail: genSVG(002),
    voiceTip: "单手轻轻撩一下耳边头发，下巴微微抬起",
    category: "室内日常",
    version: 5,
  },
  {
    id: "template_003",
    description: "托腮思考，文艺感十足，适合近景特写",
    overlayUrl: genSVG(003),
    thumbnail: genSVG(003),
    voiceTip: "用手托住一边脸，眼睛看我，眼神温柔一点",
    category: "室内日常",
    version: 5,
  },
  {
    id: "template_004",
    description: "先拍背影，再慢慢转身抓拍，自然又有故事感",
    overlayUrl: genSVG(004),
    thumbnail: genSVG(004),
    voiceTip: "先背对我，然后慢慢转身，回头那一瞬间按下快门！",
    category: "室内日常",
    version: 5,
  },
  {
    id: "template_005",
    description: "手托咖啡杯，文艺小资感溢出屏幕",
    overlayUrl: genSVG(005),
    thumbnail: genSVG(005),
    voiceTip: "双手捧杯，眼睛看镜头，嘴角微微上扬～",
    category: "室内场景",
    version: 5,
  },
  {
    id: "template_006",
    description: "站在书架前，自然翻书或靠在书架旁",
    overlayUrl: genSVG(006),
    thumbnail: genSVG(006),
    voiceTip: "随手拿本书，或者靠在书架旁边，看书看我随你～",
    category: "室内场景",
    version: 5,
  },
  {
    id: "template_007",
    description: "倚靠沙发，慵懒又可爱，居家感十足",
    overlayUrl: genSVG(007),
    thumbnail: genSVG(007),
    voiceTip: "靠在沙发上，一只手撑着脸，看镜头笑一个～",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_008",
    description: "海边跑起来抓拍，动感十足超出片",
    overlayUrl: genSVG(008),
    thumbnail: genSVG(008),
    voiceTip: "在海边慢慢跑起来，裙摆飞扬的瞬间抓拍！",
    category: "户外风景",
    version: 5,
  },
  {
    id: "template_009",
    description: "樱花飘落，浪漫满分的春日人像",
    overlayUrl: genSVG(009),
    thumbnail: genSVG(009),
    voiceTip: "站在樱花树下，抬头看花，让花瓣落在头发上～",
    category: "户外风景",
    version: 5,
  },
  {
    id: "template_010",
    description: "自然走路抓拍，时尚街拍感信手拈来",
    overlayUrl: genSVG(010),
    thumbnail: genSVG(010),
    voiceTip: "往前走别回头，自然地走起来，我抓拍你！",
    category: "城市街拍",
    version: 5,
  },
  {
    id: "template_011",
    description: "天台夕阳剪影，氛围感大片",
    overlayUrl: genSVG(011),
    thumbnail: genSVG(011),
    voiceTip: "站在天台边缘，背光拍摄，剪影超有感觉～",
    category: "户外风景",
    version: 5,
  },
  {
    id: "template_012",
    description: "下午茶甜点时刻，优雅精致的女孩",
    overlayUrl: genSVG(012),
    thumbnail: genSVG(012),
    voiceTip: "拿起甜品勺或茶杯，侧一点脸庞，嘴角带笑～",
    category: "室内场景",
    version: 5,
  },
  {
    id: "template_013",
    description: "火锅美食照，热气腾腾的生活气",
    overlayUrl: genSVG(013),
    thumbnail: genSVG(013),
    voiceTip: "对着火锅举筷子，让热气模糊一点点脸庞，氛围感拉满！",
    category: "餐厅美食",
    version: 5,
  },
  {
    id: "template_014",
    description: "复古穿搭胶片风，穿越时光的美",
    overlayUrl: genSVG(014),
    thumbnail: genSVG(014),
    voiceTip: "戴上复古发带，下巴微微抬起，眼神带点故事感～",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_015",
    description: "运动装扮，活力满满的运动女孩",
    overlayUrl: genSVG(015),
    thumbnail: genSVG(015),
    voiceTip: "双手比个耶，或者举过头顶，笑得灿烂一点！",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_016",
    description: "城市夜景，霓虹灯光中美美出镜",
    overlayUrl: genSVG(016),
    thumbnail: genSVG(016),
    voiceTip: "让身后的灯光在脸上形成光斑，眼睛看我，别眨眼～",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_017",
    description: "雨天窗边，文艺清新的氛围感",
    overlayUrl: genSVG(017),
    thumbnail: genSVG(017),
    voiceTip: "靠在窗边，看窗外或看镜头，让雨水成为背景～",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_018",
    description: "两人牵手背影，甜蜜又浪漫",
    overlayUrl: genSVG(018),
    thumbnail: genSVG(018),
    voiceTip: "两人背对镜头，手牵手站好，男友从背后揽住你的腰～",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_019",
    description: "被从背后环抱，甜甜的情侣照",
    overlayUrl: genSVG(019),
    thumbnail: genSVG(019),
    voiceTip: "女友站着别动，男友从后面抱住，然后一起看镜头～",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_020",
    description: "两人对视，甜蜜温馨的情侣瞬间",
    overlayUrl: genSVG(020),
    thumbnail: genSVG(020),
    voiceTip: "两人面对面，你看着我我看着你，笑着抓拍～",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_021",
    description: "背对镜头牵手，简约又甜蜜",
    overlayUrl: genSVG(021),
    thumbnail: genSVG(021),
    voiceTip: "两人背对镜头，手自然垂在两侧牵着，头微微侧一点～",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_022",
    description: "生日帽+蛋糕，温馨甜蜜的生日纪念",
    overlayUrl: genSVG(022),
    thumbnail: genSVG(022),
    voiceTip: "戴上生日帽，双手捧脸笑一个，准备许愿吹蜡烛！",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_023",
    description: "毕业袍+抛帽，定格青春的高光时刻",
    overlayUrl: genSVG(023),
    thumbnail: genSVG(023),
    voiceTip: "穿上毕业袍，把帽子抛向天空，笑得灿烂点！",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_024",
    description: "地标建筑前，旅行感满满的打卡照",
    overlayUrl: genSVG(024),
    thumbnail: genSVG(024),
    voiceTip: "背对地标建筑，一只手比耶，头微微抬起看向镜头～",
    category: "情侣合照",
    version: 5,
  },
  {
    id: "template_025",
    description: "和萌宠一起入镜，温馨有爱的瞬间",
    overlayUrl: genSVG(025),
    thumbnail: genSVG(025),
    voiceTip: "蹲下或坐下，让宠物在旁边，然后看向镜头笑～",
    category: "特殊风格",
    version: 5,
  },
  {
    id: "template_026",
    description: "面对面坐着喝咖啡，文艺感满满的约会照",
    overlayUrl: genSVG(026),
    thumbnail: genSVG(026),
    voiceTip: "两个人对坐，手捧咖啡杯，看向镜头笑一个～",
    category: "城市街拍",
    version: 6,
  },
  {
    id: "template_027",
    description: "城市感满满的通勤打卡照，靠着栏杆随性又好看",
    overlayUrl: genSVG(027),
    thumbnail: genSVG(027),
    voiceTip: "靠在站台的栏杆上，一只手扶着，头微微抬起看镜头～",
    category: "城市街拍",
    version: 6,
  },
  {
    id: "template_028",
    description: "夕阳剪影超有氛围，漫步海边定格浪漫瞬间",
    overlayUrl: genSVG(028),
    thumbnail: genSVG(028),
    voiceTip: "面向大海，背后是夕阳，侧身站好，手可以插兜或撩头发～",
    category: "户外风景",
    version: 6,
  },
  {
    id: "template_029",
    description: "文艺小清新，在书架前拿本书随意一站就很好看",
    overlayUrl: genSVG(029),
    thumbnail: genSVG(029),
    voiceTip: "拿一本书靠在书架旁边，低头看书或抬头看镜头，文艺感拉满～",
    category: "室内场景",
    version: 6,
  },
  {
    id: "template_030",
    description: "一起下厨的甜蜜日常，灶台前轻松自然的互动感",
    overlayUrl: genSVG(030),
    thumbnail: genSVG(030),
    voiceTip: "在灶台前假装炒菜，自然一点看镜头，笑容灿烂～",
    category: "餐厅美食",
    version: 6,
  },
  {
    id: "template_031",
    description: "浴室镜前自拍，光线均匀超显气质",
    overlayUrl: genSVG(031),
    thumbnail: genSVG(031),
    voiceTip: "对着镜子站好，侧身45度，笑一个～",
    category: "室内场景",
    version: 7,
  },
  {
    id: "template_032",
    description: "星空下仰望，夜空璀璨超有氛围感",
    overlayUrl: genSVG(032),
    thumbnail: genSVG(032),
    voiceTip: "抬头看星空，脸微微抬起，让星光落在眼睛里～",
    category: "户外风景",
    version: 7,
  },
  {
    id: "template_033",
    description: "公园长椅上的午后时光，慵懒又治愈",
    overlayUrl: genSVG(033),
    thumbnail: genSVG(033),
    voiceTip: "坐在长椅上，一只手撑着，侧头看向镜头～",
    category: "户外风景",
    version: 7,
  },
  {
    id: "template_034",
    description: "泳池边比基尼，阳光泳池超有夏威夷感",
    overlayUrl: genSVG(034),
    thumbnail: genSVG(034),
    voiceTip: "坐在泳池边，一只手撑在身后，看镜头笑～",
    category: "餐厅美食",
    version: 7,
  },
  {
    id: "template_035",
    description: "复古装修的咖啡馆里，穿越感十足",
    overlayUrl: genSVG(035),
    thumbnail: genSVG(035),
    voiceTip: "坐在复古沙发上，歪头看镜头，文艺感满满～",
    category: "城市街拍",
    version: 7,
  },
  {
    id: "template_036",
    description: "音乐节现场，摇滚酷girl风超有感染力",
    overlayUrl: genSVG(036),
    thumbnail: genSVG(036),
    voiceTip: "举起双手跟着节奏摇摆，笑容灿烂抓拍～",
    category: "特殊风格",
    version: 7,
  },
  {
    id: "template_037",
    description: "画廊看展，文艺气质拉满的艺术感",
    overlayUrl: genSVG(037),
    thumbnail: genSVG(037),
    voiceTip: "站在画作旁边侧身，回头看镜头，文艺感十足～",
    category: "特殊风格",
    version: 7,
  },
  {
    id: "template_038",
    description: "露营篝火旁，暖暖火光映在脸上的氛围感",
    overlayUrl: genSVG(038),
    thumbnail: genSVG(038),
    voiceTip: "围着篝火侧身站，让火光打在侧脸上，超有感觉～",
    category: "户外风景",
    version: 7,
  },
  {
    id: "template_039",
    description: "摩天轮里俯瞰城市，浪漫又唯美的体验",
    overlayUrl: genSVG(039),
    thumbnail: genSVG(039),
    voiceTip: "靠在摩天轮窗边，看向窗外或镜头，浪漫感拉满～",
    category: "特殊风格",
    version: 7,
  },
  {
    id: "template_040",
    description: "超市货架前拿道具互动，搞怪可爱趣味十足",
    overlayUrl: genSVG(040),
    thumbnail: genSVG(040),
    voiceTip: "拿起货架上的零食或水果，俏皮地看向镜头～",
    category: "餐厅美食",
    version: 7,
  },
  {
    id: "template_041",
    description: "草地野餐小清新，蓝天白云绿草超有活力",
    overlayUrl: genSVG(041),
    thumbnail: genSVG(041),
    voiceTip: "坐在野餐垫上，一手撑草地，侧头对我笑一个～",
    category: "餐厅美食",
    version: 15,
  },
  {
    id: "template_042",
    description: "便利店门口日常感，零食饮料做道具俏皮可爱",
    overlayUrl: genSVG(042),
    thumbnail: genSVG(042),
    voiceTip: "站在便利店门口，手里拿着零食饮料，俏皮看镜头～",
    category: "户外风景",
    version: 15,
  },
  {
    id: "template_043",
    description: "绿植环绕的温室花园，清新自然氧气感",
    overlayUrl: genSVG(043),
    thumbnail: genSVG(043),
    voiceTip: "站在温室绿植前，低头闻花香或抬头看镜头，超清新～",
    category: "室内场景",
    version: 15,
  },
  {
    id: "template_044",
    description: "火车轨道文艺感，铁轨延伸超有电影感",
    overlayUrl: genSVG(044),
    thumbnail: genSVG(044),
    voiceTip: "站在火车轨道边，侧身看镜头，超有电影感～",
    category: "城市街拍",
    version: 15,
  },
  {
    id: "template_045",
    description: "便利店零食互动，俏皮可爱的日常感",
    overlayUrl: genSVG(045),
    thumbnail: genSVG(045),
    voiceTip: "拿起便利店的零食，俏皮地举起来看镜头～",
    category: "室内日常",
    version: 15,
  },
  {
    id: "template_046",
    description: "天台露台派对，夜景璀璨超有氛围感",
    overlayUrl: genSVG(046),
    thumbnail: genSVG(046),
    voiceTip: "站在天台露台，背靠城市灯光，侧身笑一个～",
    category: "室内场景",
    version: 15,
  },
  {
    id: "template_047",
    description: "湖边水面倒影超浪漫，波光粼粼氛围感",
    overlayUrl: genSVG(047),
    thumbnail: genSVG(047),
    voiceTip: "站在湖边，低头看水面或抬头看镜头，超浪漫～",
    category: "户外风景",
    version: 15,
  },
  {
    id: "template_048",
    description: "商场橱窗灯光美，时尚都市感十足",
    overlayUrl: genSVG(048),
    thumbnail: genSVG(048),
    voiceTip: "靠在商场橱窗前，让灯光打在脸上，超有都市感～",
    category: "城市街拍",
    version: 15,
  },
  {
    id: "template_049",
    description: "酒吧氛围灯光暗，霓虹光影超有感觉",
    overlayUrl: genSVG(049),
    thumbnail: genSVG(049),
    voiceTip: "靠在吧台边，让灯光打在侧脸上，超有氛围～",
    category: "城市街拍",
    version: 15,
  },
  {
    id: "template_050",
    description: "寺庙古建筑前，超有禅意和历史感",
    overlayUrl: genSVG(050),
    thumbnail: genSVG(050),
    voiceTip: "站在古建筑前，侧身回眸或正面看镜头，古风感十足～",
    category: "户外风景",
    version: 15,
  },
  {
    id: "template_051",
    description: "海边夕阳余晖，逆光剪影超级浪漫，海风吹起发丝超有感觉～",
    overlayUrl: genSVG(051),
    thumbnail: genSVG(051),
    voiceTip: "背对夕阳，侧身看镜头，让海风吹起头发，超浪漫～",
    category: "户外风景",
    version: 9,
  },
  {
    id: "template_052",
    description: "咖啡馆窗边小资情调，捧着咖啡看着窗外或者和镜头互动都超好看",
    overlayUrl: genSVG(052),
    thumbnail: genSVG(052),
    voiceTip: "捧一杯咖啡，靠在窗边，眼神看向窗外或轻轻看镜头～",
    category: "城市街拍",
    version: 9,
  },
  {
    id: "template_053",
    description: "春天樱花盛开，粉嫩背景超级少女，站着坐着都好看",
    overlayUrl: genSVG(053),
    thumbnail: genSVG(053),
    voiceTip: "站在樱花树下，抬头看花或者侧头微笑，超级有氛围～",
    category: "户外风景",
    version: 9,
  },
  {
    id: "template_054",
    description: "城市天台俯瞰夜景，霓虹灯光闪烁，都市感与浪漫感并存",
    overlayUrl: genSVG(054),
    thumbnail: genSVG(054),
    voiceTip: "站在天台边缘，背景是城市灯光，低头微笑或侧身看镜头～",
    category: "户外风景",
    version: 9,
  },
  {
    id: "template_055",
    description: "文艺书店里翻书或者站在书架前，文静气质瞬间拉满",
    overlayUrl: genSVG(055),
    thumbnail: genSVG(055),
    voiceTip: "站在书架前，随手拿本书，低头看书或抬头看镜头，文静感十足～",
    category: "室内场景",
    version: 9,
  },
  {
    id: "template_056",
    description: "便利店随手一拍，零食饮料做道具，俏皮可爱",
    overlayUrl: genSVG(056),
    thumbnail: genSVG(056),
    voiceTip: "拿起便利店的零食或饮料，俏皮地看向镜头～",
    category: "室内日常",
    version: 10,
  },
  {
    id: "template_057",
    description: "草地野餐小清新，草帽配阳光，自然又有活力",
    overlayUrl: genSVG(057),
    thumbnail: genSVG(057),
    voiceTip: "坐在野餐垫上，一手撑着草地，侧头微笑～",
    category: "餐厅美食",
    version: 10,
  },
  {
    id: "template_058",
    description: "花店里捧着鲜花，甜美又少女感十足",
    overlayUrl: genSVG(058),
    thumbnail: genSVG(058),
    voiceTip: "捧一束鲜花，低头闻花香或抬头看镜头，甜美感拉满～",
    category: "餐厅美食",
    version: 10,
  },
  {
    id: "template_059",
    description: "古镇老街巷子里，文艺复古感拉满",
    overlayUrl: genSVG(059),
    thumbnail: genSVG(059),
    voiceTip: "站在古镇巷子里，靠着老墙，侧身回眸看镜头～",
    category: "户外风景",
    version: 10,
  },
  {
    id: "template_060",
    description: "城市高楼大厦背景，都市精英感十足",
    overlayUrl: genSVG(060),
    thumbnail: genSVG(060),
    voiceTip: "背靠高楼，仰头看镜头，都市感瞬间拉满～",
    category: "城市街拍",
    version: 10,
  },
  {
    id: "template_061",
    description: "超市货架前互动，生活气息满满",
    overlayUrl: genSVG(061),
    thumbnail: genSVG(061),
    voiceTip: "拿起超市里的零食或水果，俏皮地看向镜头～",
    category: "城市街拍",
    version: 10,
  },
  {
    id: "template_062",
    description: "圣诞树前许愿，节日氛围感满满",
    overlayUrl: genSVG(062),
    thumbnail: genSVG(062),
    voiceTip: "站在圣诞树旁，抬头看灯饰或者侧身微笑，节日感拉满～",
    category: "室内场景",
    version: 10,
  },
  {
    id: "template_063",
    description: "校园操场跑道，青春活力校园感",
    overlayUrl: genSVG(063),
    thumbnail: genSVG(063),
    voiceTip: "站在跑道上，一只手插兜，看镜头灿烂一笑～",
    category: "特殊风格",
    version: 10,
  },
  {
    id: "template_064",
    description: "演唱会现场应援，偶像感满满",
    overlayUrl: genSVG(064),
    thumbnail: genSVG(064),
    voiceTip: "举起荧光棒或双手，比个爱心，表情夸张灿烂～",
    category: "特殊风格",
    version: 10,
  },
  {
    id: "template_065",
    description: "美术馆极简白墙，高级感时尚大片",
    overlayUrl: genSVG(065),
    thumbnail: genSVG(065),
    voiceTip: "站在纯白墙前，穿搭简约，侧身回眸超有高级感～",
    category: "特殊风格",
    version: 10,
  },
  {
    id: "template_066",
    description: "雪地里穿滑雪服，雪花飘落超有冬日感",
    overlayUrl: genSVG(066),
    thumbnail: genSVG(066),
    voiceTip: "站在雪地里，捧一把雪或回头微笑，冬日感拉满～",
    category: "户外风景",
    version: 11,
  },
  {
    id: "template_067",
    description: "海边木栈道散步，海风吹起裙摆超浪漫",
    overlayUrl: genSVG(067),
    thumbnail: genSVG(067),
    voiceTip: "走在栈道上，回眸一笑，让海风吹起头发～",
    category: "户外风景",
    version: 11,
  },
  {
    id: "template_068",
    description: "家里绿植前，自然清新的居家感",
    overlayUrl: genSVG(068),
    thumbnail: genSVG(068),
    voiceTip: "站在绿植旁边，自然微笑，看镜头或低头看植物～",
    category: "室内场景",
    version: 11,
  },
  {
    id: "template_069",
    description: "游乐园旋转飞椅上，尖叫与快乐并存",
    overlayUrl: genSVG(069),
    thumbnail: genSVG(069),
    voiceTip: "坐在飞椅上，双手举起，笑得开心灿烂～",
    category: "特殊风格",
    version: 11,
  },
  {
    id: "template_070",
    description: "海边礁石上海浪拍打，帅气又浪漫",
    overlayUrl: genSVG(070),
    thumbnail: genSVG(070),
    voiceTip: "站在礁石上，侧身看向大海，让海浪声成为背景～",
    category: "户外风景",
    version: 11,
  },
  {
    id: "template_071",
    description: "音乐节现场跟着节奏摇摆，尽情释放快乐",
    overlayUrl: genSVG(071),
    thumbnail: genSVG(071),
    voiceTip: "跟着节拍摇摆，双手举起，表情夸张灿烂，活力满满～",
    category: "特殊风格",
    version: 12,
  },
  {
    id: "template_072",
    description: "图书馆安静看书，文静气质瞬间拉满",
    overlayUrl: genSVG(072),
    thumbnail: genSVG(072),
    voiceTip: "坐在书桌前，一手托腮，眼神看向书本或侧头微笑～",
    category: "特殊风格",
    version: 12,
  },
  {
    id: "template_073",
    description: "便利店零食货架前，俏皮日常感",
    overlayUrl: genSVG(073),
    thumbnail: genSVG(073),
    voiceTip: "从货架上拿一瓶饮料或零食，俏皮地看向镜头笑～",
    category: "室内日常",
    version: 12,
  },
  {
    id: "template_074",
    description: "健身房大镜子前，运动活力满满",
    overlayUrl: genSVG(074),
    thumbnail: genSVG(074),
    voiceTip: "在健身房镜子前，一手插兜或靠在器械旁，自信看镜头～",
    category: "室内场景",
    version: 12,
  },
  {
    id: "template_075",
    description: "经典九宫格构图引导，精准定位人脸位置",
    overlayUrl: genSVG(075),
    thumbnail: genSVG(075),
    voiceTip: "让头部和眼睛落在上方横线交叉点，构图完美～",
    category: "室内场景",
    version: 12,
  },
  {
    id: "template_076",
    description: "站在窗帘旁让阳光透进来，逆光超有氛围",
    overlayUrl: genSVG(076),
    thumbnail: genSVG(076),
    voiceTip: "站在窗帘旁边，让阳光从背后透进来，微微转身让光打在侧脸上～",
    category: "室内场景",
    version: 16,
  },
  {
    id: "template_077",
    description: "躺在阳台躺椅上，夏日午后的慵懒感",
    overlayUrl: genSVG(077),
    thumbnail: genSVG(077),
    voiceTip: "躺在阳台躺椅上，一只手撑着脸，看镜头笑一个，慵懒又可爱～",
    category: "室内场景",
    version: 16,
  },
  {
    id: "template_078",
    description: "站在涂鸦墙前，潮流感十足",
    overlayUrl: genSVG(078),
    thumbnail: genSVG(078),
    voiceTip: "靠在涂鸦墙前，双手插兜或比个pose，酷酷地看向镜头～",
    category: "城市街拍",
    version: 16,
  },
  {
    id: "template_079",
    description: "车里自拍也能很有氛围感，侧身看向窗外超有故事感",
    overlayUrl: genSVG(079),
    thumbnail: genSVG(079),
    voiceTip: "侧身坐在车里，打开车窗让光线进来，看向窗外笑一个～",
    category: "特殊风格",
    version: 13,
  },
  {
    id: "template_080",
    description: "便利店门口俏皮日常，零食道具互动超可爱",
    overlayUrl: genSVG(080),
    thumbnail: genSVG(080),
    voiceTip: "站在便利店门口，手里拿着零食饮料，俏皮地看镜头笑～",
    category: "室内日常",
    version: 13,
  },
  // ===== 新增模板 081-090 =====
  {
    id: "template_081",
    description: "健身房动感单车，活力满满的运动少女",
    overlayUrl: genSVG(081),
    thumbnail: genSVG(081),
    voiceTip: "骑上动感单车，身体微微前倾，笑着看向镜头，活力满满！",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_082",
    description: "厨房烹饪时刻，围裙配美食超有生活感",
    overlayUrl: genSVG(082),
    thumbnail: genSVG(082),
    voiceTip: "站在灶台前，一手拿锅铲或端着菜，笑得灿烂点！",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_083",
    description: "温泉泡汤超放松，蒸汽氤氲超级治愈",
    overlayUrl: genSVG(083),
    thumbnail: genSVG(083),
    voiceTip: "靠在温泉边，让蒸汽打在脸上，自然微笑看向镜头～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_084",
    description: "公交站等车，日常感满满的城市街拍",
    overlayUrl: genSVG(084),
    thumbnail: genSVG(084),
    voiceTip: "站在公交站牌下，靠着站牌，看镜头或看远方～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_085",
    description: "操场单杠运动风，阳光活力校园感",
    overlayUrl: genSVG(085),
    thumbnail: genSVG(085),
    voiceTip: "站在单杠旁边或操场跑道，身体舒展，笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_086",
    description: "音乐节舞台狂欢，跟着节奏尽情释放",
    overlayUrl: genSVG(086),
    thumbnail: genSVG(086),
    voiceTip: "双手举起跟着节拍摇摆，表情夸张灿烂，活力四射！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_087",
    description: "艺术展画廊看展，文静知性的艺术少女",
    overlayUrl: genSVG(087),
    thumbnail: genSVG(087),
    voiceTip: "站在艺术品旁边，侧头微笑或者假装欣赏画作，文艺感拉满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_088",
    description: "便利店自助结账，日常感的俏皮瞬间",
    overlayUrl: genSVG(088),
    thumbnail: genSVG(088),
    voiceTip: "站在自助结账机前，手里拿着商品，俏皮地看镜头笑～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_089",
    description: "公园草坪野餐，阳光草地的清新感",
    overlayUrl: genSVG(089),
    thumbnail: genSVG(089),
    voiceTip: "坐在野餐垫上，一手撑着草地，侧头微笑看向镜头～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_090",
    description: "地铁站台等车，都市通勤的日常感",
    overlayUrl: genSVG(090),
    thumbnail: genSVG(090),
    voiceTip: "站在地铁站台上，靠着柱子或看向远处，文艺又日常～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_091",
    name: "窗边逆光",
    description: "窗边逆光剪影，氛围感拉满",
    overlayUrl: genSVG(091),
    thumbnail: genSVG(091),
    voiceTip: "站在窗边，背对光源，让光线勾勒出轮廓，侧头看镜头～",
    category: "室内人像",
    version: 1,
  },
  {
    id: "template_092",
    name: "镜子自拍",
    description: "对着镜子自拍，找好角度",
    overlayUrl: genSVG(092),
    thumbnail: genSVG(092),
    voiceTip: "对着镜子找好角度，手机稍微侧一点避免反光，歪头微笑～",
    category: "自拍技巧",
    version: 1,
  },
  {
    id: "template_093",
    name: "书架前文艺",
    description: "书架前随手拿本书，文艺感十足",
    overlayUrl: genSVG(093),
    thumbnail: genSVG(093),
    voiceTip: "站在书架前，随手翻起一本书，微微低头看书，嘴角带笑～",
    category: "室内人像",
    version: 1,
  },
  {
    id: "template_094",
    name: "双栏杆前景",
    description: "双栏杆做前景虚化，层次感强",
    overlayUrl: genSVG(094),
    thumbnail: genSVG(094),
    voiceTip: "找两根栏杆做前景，手机对焦在你身上，让背景虚化更有层次～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_095",
    name: "三点光源",
    description: "三点布光练习，影视级打光",
    overlayUrl: genSVG(095),
    thumbnail: genSVG(095),
    voiceTip: "想象有三个光源：正面主光、侧面辅光、逆光轮廓——找到最立体的角度～",
    category: "室内人像",
    version: 1,
  },
  {
    id: "template_096",
    name: "黄金时段",
    description: "日落前后黄金时段，光线最柔",
    overlayUrl: genSVG(096),
    thumbnail: genSVG(096),
    voiceTip: "日落前后半小时是拍照黄金时间！让男友蹲低一点，仰拍更显瘦～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_097",
    name: "水面反光",
    description: "水边拍照，倒影和水波超有氛围",
    overlayUrl: genSVG(097),
    thumbnail: genSVG(097),
    voiceTip: "在水边找好角度，让倒影进入画面，轻风吹起发丝，动态抓拍～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_098",
    name: "九宫格三分",
    description: "打开九宫格，人物放在交叉点",
    overlayUrl: genSVG(098),
    thumbnail: genSVG(098),
    voiceTip: "打开相机网格线，把你的脸放在四个交叉点的任意一个，构图立刻变专业～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_099",
    name: "隧道纵深",
    description: "站在隧道里，利用纵深构图",
    overlayUrl: genSVG(099),
    thumbnail: genSVG(099),
    voiceTip: "站在隧道里，让男友在远处拍你，利用隧道纵深构图，超有电影感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_100",
    name: "十字构图",
    description: "十字构图法，交叉点放主体",
    overlayUrl: genSVG(100),
    thumbnail: genSVG(100),
    voiceTip: "找有线条的场景（道路、走廊），把人放在线条交叉点，构图立刻变高级～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_101",
    name: "菱形框架构图",
    description: "找菱形或钻石形状的场景（窗户、镜子、地砖），把人放在菱形中心，构图立刻高级起来～",
    overlayUrl: genSVG(101),
    thumbnail: genSVG(101),
    voiceTip: "找菱形或钻石形状的场景（窗户、镜子、地砖），把人放在菱形中心，构图立刻高级起来～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_102",
    name: "螺旋生长",
    description: "找有螺旋元素的场景（楼梯、贝壳、旋涡），顺着螺旋构图，画面超有动感～",
    overlayUrl: genSVG(102),
    thumbnail: genSVG(102),
    voiceTip: "找有螺旋元素的场景（楼梯、贝壳、旋涡），顺着螺旋构图，画面超有动感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_103",
    name: "镜像对称",
    description: "找对称的场景（镜面、玻璃、水面），利用对称反射增加层次感～",
    overlayUrl: genSVG(103),
    thumbnail: genSVG(103),
    voiceTip: "找对称的场景（镜面、玻璃、水面），利用对称反射增加层次感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_104",
    name: "三角山峰",
    description: "找有山峰或尖顶的场景，让人物站在三角形的顶点，超有气势～",
    overlayUrl: genSVG(104),
    thumbnail: genSVG(104),
    voiceTip: "找有山峰或尖顶的场景，让人物站在三角形的顶点，超有气势～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_105",
    name: "波浪地平线",
    description: "找波浪形或起伏的场景，利用曲线构图，画面柔美又流畅～",
    overlayUrl: genSVG(105),
    thumbnail: genSVG(105),
    voiceTip: "找波浪形或起伏的场景，利用曲线构图，画面柔美又流畅～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_106",
    name: "星光绽放",
    description: "找发光源或有星芒的场景，让光芒从身后透出，超有仙气～",
    overlayUrl: genSVG(106),
    thumbnail: genSVG(106),
    voiceTip: "找发光源或有星芒的场景，让光芒从身后透出，超有仙气～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_107",
    name: "渐变纵深",
    description: "找有明暗对比的场景，让光线形成纵深感，立体感立刻拉满～",
    overlayUrl: genSVG(107),
    thumbnail: genSVG(107),
    voiceTip: "找有明暗对比的场景，让光线形成纵深感，立体感立刻拉满～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_108",
    name: "圆形统一",
    description: "找圆形元素（镜子、拱门、窗户），利用圆形构图，画面完整又有焦点～",
    overlayUrl: genSVG(108),
    thumbnail: genSVG(108),
    voiceTip: "找圆形元素（镜子、拱门、窗户），利用圆形构图，画面完整又有焦点～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_109",
    name: "网格矩阵",
    description: "找网格或格子场景（窗格、铁丝网），打破网格制造张力，超有艺术感～",
    overlayUrl: genSVG(109),
    thumbnail: genSVG(109),
    voiceTip: "找网格或格子场景（窗格、铁丝网），打破网格制造张力，超有艺术感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_110",
    name: "弧形彩虹",
    description: "找弧形元素（彩虹、拱桥、隧道），顺着弧线构图，画面有延伸感～",
    overlayUrl: genSVG(110),
    thumbnail: genSVG(110),
    voiceTip: "找弧形元素（彩虹、拱桥、隧道），顺着弧线构图，画面有延伸感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_111",
    name: "光影分割",
    description: "找有明显光影分界的场景，让光线切割画面，形成戏剧感～",
    overlayUrl: genSVG(111),
    thumbnail: genSVG(111),
    voiceTip: "找有明显光影分界的场景，让光线切割画面，形成戏剧感～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_112",
    name: "同心圆环",
    description: "找同心圆元素（靶心、涟漪、漩涡），利用圆环构图，焦点超明确～",
    overlayUrl: genSVG(112),
    thumbnail: genSVG(112),
    voiceTip: "找同心圆元素（靶心、涟漪、漩涡），利用圆环构图，焦点超明确～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_113",
    name: "之字动感",
    description: "找有锯齿或曲折线条的场景，之字构图充满活力和动感～",
    overlayUrl: genSVG(113),
    thumbnail: genSVG(113),
    voiceTip: "找有锯齿或曲折线条的场景，之字构图充满活力和动感～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_114",
    name: "辐射线条",
    description: "找有辐射线条的场景（光芒、射灯、铁路），从中心向外辐射，画面张力十足～",
    overlayUrl: genSVG(114),
    thumbnail: genSVG(114),
    voiceTip: "找有辐射线条的场景（光芒、射灯、铁路），从中心向外辐射，画面张力十足～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_115",
    name: "窗格图案",
    description: "找有规则的窗格场景，让人物打破规则，构图立刻有趣起来～",
    overlayUrl: genSVG(115),
    thumbnail: genSVG(115),
    voiceTip: "找有规则的窗格场景，让人物打破规则，构图立刻有趣起来～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_116",
    name: "分形树叶",
    description: "找有自然叶脉或树枝的场景，利用自然线条，画面清新又有生机～",
    overlayUrl: genSVG(116),
    thumbnail: genSVG(116),
    voiceTip: "找有自然叶脉或树枝的场景，利用自然线条，画面清新又有生机～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_117",
    name: "倒影水池",
    description: "找有水面或玻璃的场景，利用倒影增加层次，对称又梦幻～",
    overlayUrl: genSVG(117),
    thumbnail: genSVG(117),
    voiceTip: "找有水面或玻璃的场景，利用倒影增加层次，对称又梦幻～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_118",
    name: "六边形阵",
    description: "找六边形或蜂巢场景，规律的几何图形让构图更有设计感～",
    overlayUrl: genSVG(118),
    thumbnail: genSVG(118),
    voiceTip: "找六边形或蜂巢场景，规律的几何图形让构图更有设计感～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_119",
    name: "光之走廊",
    description: "找走廊或纵深感强的场景，让光线引导视线，画面深邃又神秘～",
    overlayUrl: genSVG(119),
    thumbnail: genSVG(119),
    voiceTip: "找走廊或纵深感强的场景，让光线引导视线，画面深邃又神秘～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_120",
    name: "宇宙漩涡",
    description: "找旋涡或星系元素的场景，螺旋构图超有宇宙感，大片感拉满～",
    overlayUrl: genSVG(120),
    thumbnail: genSVG(120),
    voiceTip: "找旋涡或星系元素的场景，螺旋构图超有宇宙感，大片感拉满～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_121",
    name: "健身房瑜伽垫",
    description: "瑜伽垫或健身房背景，运动感满满，活力女孩超好看～",
    overlayUrl: genSVG(121),
    thumbnail: genSVG(121),
    voiceTip: "站在瑜伽垫上，侧身看我或者伸手比个耶，活力满满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_122",
    name: "古城墙前",
    description: "古城墙或长城背景，历史感与文艺感并存，超有氛围～",
    overlayUrl: genSVG(122),
    thumbnail: genSVG(122),
    voiceTip: "靠在古城墙边，侧身回眸，让历史感加分～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_123",
    name: "沙漠戈壁",
    description: "沙漠或戈壁背景，广袤天地间的大片感，超有冲击力～",
    overlayUrl: genSVG(123),
    thumbnail: genSVG(123),
    voiceTip: "站在沙漠中，抬头看镜头，让广袤的背景衬出大气感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_124",
    name: "樱花隧道",
    description: "樱花盛开的树下或樱花隧道，粉嫩浪漫超有氛围感～",
    overlayUrl: genSVG(124),
    thumbnail: genSVG(124),
    voiceTip: "站在樱花树下，抬头看花瓣飘落，让樱花点缀画面～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_125",
    name: "瀑布溪流前",
    description: "瀑布或溪流背景，水汽氤氲超有清新感，大自然感拉满～",
    overlayUrl: genSVG(125),
    thumbnail: genSVG(125),
    voiceTip: "站在瀑布或溪流前，让水汽打在脸上，自然感满满～",
    category: "户外风景",
    version: 1,
  },
  // ========== Round 20 新增模板 126-130 ==========
  {
    id: "template_126",
    name: "超市货架前",
    description: "超市货架做背景超有生活感！拿着零食道具，俏皮看镜头～",
    overlayUrl: genSVG(126),
    thumbnail: genSVG(126),
    voiceTip: "超市货架前光线均匀！拿个零食道具，俏皮地看镜头笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_127",
    name: "海边栈道漫步",
    description: "海边栈道上光线通透！背对大海侧身站，海风吹起头发超有氛围～",
    overlayUrl: genSVG(127),
    thumbnail: genSVG(127),
    voiceTip: "栈道上光线超通透！背对大海侧身站，让海风吹起头发～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_128",
    name: "健身房镜前",
    description: "健身房镜前光线均匀！侧身站着，笑得灿烂超有活力～",
    overlayUrl: genSVG(128),
    thumbnail: genSVG(128),
    voiceTip: "健身房镜前光线均匀！侧身站着，笑着拍一张超有活力～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_129",
    name: "露台夕阳",
    description: "露台夕阳余晖超浪漫！逆光拍剪影超有感觉，让夕阳打在侧脸上～",
    overlayUrl: genSVG(129),
    thumbnail: genSVG(129),
    voiceTip: "露台夕阳余晖超浪漫！侧身站着让夕阳打在侧脸上～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_130",
    name: "咖啡馆角落",
    description: "咖啡馆角落光线超柔和！捧着咖啡看向窗外，文艺感满满～",
    overlayUrl: genSVG(130),
    thumbnail: genSVG(130),
    voiceTip: "咖啡馆角落光线暖暖的！捧着咖啡，侧头看窗外，文艺感十足～",
    category: "餐厅美食",
    version: 1,
  },

  {
    id: "template_131",
    name: "天台夜景",
    description: "城市高楼天台，俯瞰璀璨夜景，让女友站在天台边缘，背后是星星点点的城市灯火～",
    overlayUrl: genSVG(131),
    thumbnail: genSVG(131),
    voiceTip: "天台夜景超浪漫！靠着栏杆，让城市灯火打在侧脸上，超有氛围感～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_132",
    name: "演唱会现场",
    description: "演唱会现场灯光闪烁，音乐节超嗨！举起双手跟着节拍摇摆，表情夸张灿烂～",
    overlayUrl: genSVG(132),
    thumbnail: genSVG(132),
    voiceTip: "演唱会现场感拉满！双手举起跟着节奏摇摆，表情夸张灿烂点！",
    category: "特殊风格",
    version: 1,
  },
    {
    id: "template_133",
    name: "艺术展画廊",
    description: "画廊看展超文艺！站在艺术品旁，侧头微笑，文艺感拉满～",
    overlayUrl: genSVG(133),
    thumbnail: genSVG(133),
    voiceTip: "画廊看展超有文化感！站在艺术品旁，侧头微笑，文艺感拉满～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_134",
    name: "便利店自助结账",
    description: "自助结账机前好日常！手里拿着商品，俏皮地看镜头笑～",
    overlayUrl: genSVG(134),
    thumbnail: genSVG(134),
    voiceTip: "便利店日常感满分！手里拿着商品，俏皮地看镜头笑～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_135",
    name: "公园草坪野餐",
    description: "野餐垫上光线好温柔！坐在草地上，一手撑地，侧头微笑看向镜头～",
    overlayUrl: genSVG(135),
    thumbnail: genSVG(135),
    voiceTip: "野餐垫上光线好温柔！坐在草地上，一手撑地，侧头微笑看向镜头～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_136",
    name: "地铁站台都市",
    description: "地铁站台都市感十足！靠着柱子，看向远处，文艺日常～",
    overlayUrl: genSVG(136),
    thumbnail: genSVG(136),
    voiceTip: "地铁站台都市感十足！靠着柱子，看向远处，文艺日常～",
    category: "城市街拍",
    version: 1,
  },
    {
    id: "template_137",
    name: "便利店货架前",
    description: "货架前光线均匀！拿个零食饮料，俏皮地看镜头～",
    overlayUrl: genSVG(137),
    thumbnail: genSVG(137),
    voiceTip: "便利店货架前光线均匀！拿个零食饮料，俏皮地看镜头～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_138",
    name: "健身房器械区",
    description: "器械区背景好有运动感！侧身站着，举起哑铃或笑着看镜头～",
    overlayUrl: genSVG(138),
    thumbnail: genSVG(138),
    voiceTip: "健身房器械区背景好有运动感！侧身站着，举起哑铃或笑着看镜头～",
    category: "特殊风格",
    version: 1,
  },
    {
    id: "template_139",
    name: "厨房水槽前",
    description: "水槽前光线均匀！端着一杯水或拿着食材，笑着看镜头～",
    overlayUrl: genSVG(139),
    thumbnail: genSVG(139),
    voiceTip: "厨房水槽前光线均匀！端着一杯水或拿着食材，笑着看镜头～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_140",
    name: "图书馆自习",
    description: "图书馆安静又文艺！靠在书架旁，低头看书或者看镜头都超美～",
    overlayUrl: genSVG(140),
    thumbnail: genSVG(140),
    voiceTip: "图书馆安静又文艺！靠在书架旁，低头看书或者看镜头都超美～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_141",
    name: "露营帐篷前",
    description: "帐篷前光线超美！靠近帐篷站着，背景超有感觉～",
    overlayUrl: genSVG(141),
    thumbnail: genSVG(141),
    voiceTip: "露营帐篷前光线超美！靠近帐篷站着，背景超有感觉～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_142",
    name: "天台星空",
    description: "天台星空好美！抬头看天空，让星星落在眼睛里～",
    overlayUrl: genSVG(142),
    thumbnail: genSVG(142),
    voiceTip: "天台星空好美！抬头看天空，让星星落在眼睛里～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_143",
    name: "泳池派对",
    description: "泳池派对超嗨！靠在泳池边，笑得灿烂点～",
    overlayUrl: genSVG(143),
    thumbnail: genSVG(143),
    voiceTip: "泳池派对超嗨！靠在泳池边，笑得灿烂点～",
    category: "特殊风格",
    version: 1,
  },
    {
    id: "template_144",
    name: "便利店冰柜前",
    description: "冰柜前光线冷白！拿瓶饮料，俏皮地笑一个～",
    overlayUrl: genSVG(144),
    thumbnail: genSVG(144),
    voiceTip: "便利店冰柜前光线冷白！拿瓶饮料，俏皮地笑一个～",
    category: "室内场景",
    version: 1,
  },
    {
    id: "template_145",
    name: "海边灯塔",
    description: "灯塔背景超有画面感！侧身站着，让海风吹起头发～",
    overlayUrl: genSVG(145),
    thumbnail: genSVG(145),
    voiceTip: "海边灯塔背景超有画面感！侧身站着，让海风吹起头发～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_146",
    name: "校园操场",
    description: "校园操场运动风超阳光！站在单杠旁，身体舒展，笑一个～",
    overlayUrl: genSVG(146),
    thumbnail: genSVG(146),
    voiceTip: "校园操场运动风超阳光！站在单杠旁，身体舒展，笑一个～",
    category: "城市街拍",
    version: 1,
  },
    {
    id: "template_147",
    name: "竹林小径",
    description: "竹林小径光线斑驳！走着抓拍，自然又灵动～",
    overlayUrl: genSVG(147),
    thumbnail: genSVG(147),
    voiceTip: "竹林小径光线斑驳！走着抓拍，自然又灵动～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_148",
    name: "屋顶花园",
    description: "屋顶花园超有情调！站在花草中间，笑一个～",
    overlayUrl: genSVG(148),
    thumbnail: genSVG(148),
    voiceTip: "屋顶花园超有情调！站在花草中间，笑一个～",
    category: "户外风景",
    version: 1,
  },
    {
    id: "template_149",
    name: "烘焙甜点",
    description: "甜点柜台好诱人！端着蛋糕，笑一个～",
    overlayUrl: genSVG(149),
    thumbnail: genSVG(149),
    voiceTip: "甜点柜台好诱人！端着蛋糕，笑一个～",
    category: "餐厅美食",
    version: 1,
  },
    {
    id: "template_150",
    name: "便利店熟食区",
    description: "便利店熟食区光线均匀！拿着关东煮或饭团，俏皮地看镜头～",
    overlayUrl: genSVG(150),
    thumbnail: genSVG(150),
    voiceTip: "便利店熟食区光线均匀！拿着关东煮或饭团，俏皮地看镜头～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_151",
    name: "毕业照抛帽",
    description: "毕业袍配学士帽，抛帽的瞬间超有活力！连拍几张总有一张完美～",
    overlayUrl: genSVG(151),
    thumbnail: genSVG(151),
    voiceTip: "毕业袍配学士帽，抛帽的瞬间超有活力！连拍几张总有一张完美～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_152",
    name: "樱花树下",
    description: "樱花树下光线斑驳！风吹过来的时候按下快门，绝美～",
    overlayUrl: genSVG(152),
    thumbnail: genSVG(152),
    voiceTip: "樱花树下光线斑驳！风吹过来的时候按下快门，绝美～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_153",
    name: "健身房镜前",
    description: "健身房镜子自拍光线均匀！侧身站着，笑着拍一张超有活力～",
    overlayUrl: genSVG(153),
    thumbnail: genSVG(153),
    voiceTip: "健身房镜子自拍光线均匀！侧身站着，笑着拍一张超有活力～",
    category: "室内人像",
    version: 1,
  },
  {
    id: "template_154",
    name: "超市货架前",
    description: "超市货架前光线均匀！拿个零食饮料当道具，俏皮又自然～",
    overlayUrl: genSVG(154),
    thumbnail: genSVG(154),
    voiceTip: "超市货架前光线均匀！拿个零食饮料当道具，俏皮又自然～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_155",
    name: "古镇老街",
    description: "古镇老墙做背景超有年代感！侧身站立更有氛围～",
    overlayUrl: genSVG(155),
    thumbnail: genSVG(155),
    voiceTip: "古镇老墙做背景超有年代感！侧身站立更有氛围～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_156",
    name: "灯塔海边",
    description: "灯塔背景超有画面感！侧身站着让光线打在侧脸上～",
    overlayUrl: genSVG(156),
    thumbnail: genSVG(156),
    voiceTip: "灯塔背景超有画面感！侧身站着让光线打在侧脸上～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_157",
    name: "地铁站台",
    description: "地铁站台冷调灯光超有都市感！随意站着抓拍～",
    overlayUrl: genSVG(157),
    thumbnail: genSVG(157),
    voiceTip: "地铁站台冷调灯光超有都市感！随意站着抓拍～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_158",
    name: "农场田园",
    description: "农场田园好清新！站在田埂上或麦田里，笑一个～",
    overlayUrl: genSVG(158),
    thumbnail: genSVG(158),
    voiceTip: "农场田园好清新！站在田埂上或麦田里，笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_159",
    name: "涂鸦墙前",
    description: "涂鸦墙背景超有潮流感！靠着墙站着，酷酷地看镜头～",
    overlayUrl: genSVG(159),
    thumbnail: genSVG(159),
    voiceTip: "涂鸦墙背景超有潮流感！靠着墙站着，酷酷地看镜头～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_160",
    name: "水族馆前",
    description: "水族馆里光线超梦幻！站在大鱼缸前，笑一个～",
    overlayUrl: genSVG(160),
    thumbnail: genSVG(160),
    voiceTip: "水族馆里光线超梦幻！站在大鱼缸前，笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_161",
    name: "教堂背景",
    description: "教堂背景超庄严！端正站着，笑得温柔点～",
    overlayUrl: genSVG(161),
    thumbnail: genSVG(161),
    voiceTip: "教堂背景超庄严！端正站着，笑得温柔点～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_162",
    name: "集市摊位",
    description: "集市摊位好热闹！靠着摊位，随意自然地笑～",
    overlayUrl: genSVG(162),
    thumbnail: genSVG(162),
    voiceTip: "集市摊位好热闹！靠着摊位，随意自然地笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_163",
    name: "烘焙甜点",
    description: "面包店香气仿佛都能闻到，这张照片太有感觉了！",
    overlayUrl: genSVG(163),
    thumbnail: genSVG(163),
    voiceTip: "面包店香气仿佛都能闻到，这张照片太有感觉了！",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_164",
    name: "旋转木马",
    description: "旋转木马灯光超梦幻！抓着柱子笑一个～",
    overlayUrl: genSVG(164),
    thumbnail: genSVG(164),
    voiceTip: "旋转木马灯光超梦幻！抓着柱子笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_165",
    name: "玻璃花房",
    description: "玻璃花房光线超通透！站在植物旁边，自然微笑看向镜头～",
    overlayUrl: genSVG(165),
    thumbnail: genSVG(165),
    voiceTip: "玻璃花房光线超通透！站在植物旁边，自然微笑看向镜头～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_166",
    name: "露营帐篷",
    description: "帐篷前拍照超有户外感，男朋友这构图绝了！",
    overlayUrl: genSVG(166),
    thumbnail: genSVG(166),
    voiceTip: "帐篷前拍照超有户外感，男朋友这构图绝了！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_167",
    name: "节日装饰",
    description: "节日装饰做背景超有氛围感，让她在灯光下站好～",
    overlayUrl: genSVG(167),
    thumbnail: genSVG(167),
    voiceTip: "节日装饰做背景超有氛围感，让她在灯光下站好～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_168",
    name: "圣诞树前",
    description: "圣诞树灯光暖暖的超有氛围感！让光打在侧脸上～",
    overlayUrl: genSVG(168),
    thumbnail: genSVG(168),
    voiceTip: "圣诞树灯光暖暖的超有氛围感！让光打在侧脸上～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_169",
    name: "雨天窗边",
    description: "雨天窗边光线好柔和，在这拍超有感觉～",
    overlayUrl: genSVG(169),
    thumbnail: genSVG(169),
    voiceTip: "雨天窗边光线好柔和，在这拍超有感觉～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_170",
    name: "仰拍大长腿",
    description: "仰拍超级显腿长！男朋友蹲低，你踮起脚尖～",
    overlayUrl: genSVG(170),
    thumbnail: genSVG(170),
    voiceTip: "仰拍超级显腿长！男朋友蹲低，你踮起脚尖～",
    category: "自拍技巧",
    version: 1,
  },
  {
    id: "template_171",
    name: "镜子贴脸自拍",
    description: "镜子自拍超显脸小！贴近镜子，眼睛更有神～",
    overlayUrl: genSVG(169),
    thumbnail: genSVG(169),
    voiceTip: "镜子自拍超显脸小！贴近镜子，眼睛更有神～",
    category: "自拍技巧",
    version: 1,
  },
  {
    id: "template_172",
    name: "海边逆光剪影",
    description: "夕阳海边拍剪影超浪漫！背对太阳，轮廓超美～",
    overlayUrl: genSVG(150),
    thumbnail: genSVG(150),
    voiceTip: "夕阳海边拍剪影超浪漫！背对太阳，轮廓超美～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_173",
    name: "樱花雨抓拍",
    description: "风吹樱花飘落时按下快门，绝美瞬间～",
    overlayUrl: genSVG(130),
    thumbnail: genSVG(130),
    voiceTip: "风吹樱花飘落时按下快门，绝美瞬间～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_174",
    name: "天台城市夜景",
    description: "天台夜景超有氛围！城市灯光做背景，浪漫感拉满～",
    overlayUrl: genSVG(100),
    thumbnail: genSVG(100),
    voiceTip: "天台夜景超有氛围！城市灯光做背景，浪漫感拉满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_175",
    name: "咖啡馆窗边文艺",
    description: "咖啡馆窗边光线超温柔！捧着咖啡笑一个～",
    overlayUrl: genSVG(040),
    thumbnail: genSVG(040),
    voiceTip: "咖啡馆窗边光线超温柔！捧着咖啡笑一个～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_176",
    name: "毕业抛帽瞬间",
    description: "抛帽瞬间超有活力！让男朋友对准脸多拍几张～",
    overlayUrl: genSVG(110),
    thumbnail: genSVG(110),
    voiceTip: "抛帽瞬间超有活力！让男朋友对准脸多拍几张～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_177",
    name: "游乐场旋转木马",
    description: "旋转木马前超梦幻！侧身站着，光线超温柔～",
    overlayUrl: genSVG(095),
    thumbnail: genSVG(095),
    voiceTip: "旋转木马前超梦幻！侧身站着，光线超温柔～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_178",
    name: "健身房镜前运动风",
    description: "运动完脸微微泛红最有活力！对着镜子笑一个～",
    overlayUrl: genSVG(120),
    thumbnail: genSVG(120),
    voiceTip: "运动完脸微微泛红最有活力！对着镜子笑一个～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_179",
    name: "雪景围巾特写",
    description: "白茫茫雪地里彩色围巾超好看！特写超有氛围～",
    overlayUrl: genSVG(130),
    thumbnail: genSVG(130),
    voiceTip: "白茫茫雪地里彩色围巾超好看！特写超有氛围～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_180",
    name: "火车车窗文艺",
    description: "火车车窗光线超有故事感！侧脸望向窗外～",
    overlayUrl: genSVG(140),
    thumbnail: genSVG(140),
    voiceTip: "火车车窗光线超有故事感！侧脸望向窗外～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_181",
    name: "古镇青石板路",
    description: "古镇老街超有味道！慢慢走着让男朋友抓拍～",
    overlayUrl: genSVG(145),
    thumbnail: genSVG(145),
    voiceTip: "古镇老街超有味道！慢慢走着让男朋友抓拍～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_182",
    name: "面包房暖光特写",
    description: "面包房暖黄灯光超温馨！捧着面包笑一个～",
    overlayUrl: genSVG(050),
    thumbnail: genSVG(050),
    voiceTip: "面包房暖黄灯光超温馨！捧着面包笑一个～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_183",
    name: "水族馆海底世界",
    description: "水族馆蓝色光影超梦幻！站在鱼群前超浪漫～",
    overlayUrl: genSVG(060),
    thumbnail: genSVG(060),
    voiceTip: "水族馆蓝色光影超梦幻！站在鱼群前超浪漫～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_184",
    name: "图书馆安静时光",
    description: "图书馆光线超柔和！低头看书侧脸超好看～",
    overlayUrl: genSVG(070),
    thumbnail: genSVG(070),
    voiceTip: "图书馆光线超柔和！低头看书侧脸超好看～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_185",
    name: "草地野餐惬意",
    description: "草地野餐超惬意！躺下来俯拍，超有度假感～",
    overlayUrl: genSVG(085),
    thumbnail: genSVG(085),
    voiceTip: "草地野餐超惬意！躺下来俯拍，超有度假感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_186",
    name: "超市水果区鲜亮",
    description: "超市水果区颜色超鲜亮！拿个水果笑着拍～",
    overlayUrl: genSVG(160),
    thumbnail: genSVG(160),
    voiceTip: "超市水果区颜色超鲜亮！拿个水果笑着拍～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_187",
    name: "地铁站城市感",
    description: "地铁站超有城市感！靠在墙边侧拍，超酷～",
    overlayUrl: genSVG(165),
    thumbnail: genSVG(165),
    voiceTip: "地铁站超有城市感！靠在墙边侧拍，超酷～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_188",
    name: "帐篷露营温馨",
    description: "露营帐篷前超温馨！夜晚灯光超有氛围～",
    overlayUrl: genSVG(090),
    thumbnail: genSVG(090),
    voiceTip: "露营帐篷前超温馨！夜晚灯光超有氛围～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_189",
    name: "商场橱窗精致",
    description: "商场橱窗光线超精致！站在橱窗前超有范儿～",
    overlayUrl: genSVG(155),
    thumbnail: genSVG(155),
    voiceTip: "商场橱窗光线超精致！站在橱窗前超有范儿～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_190",
    name: "海边踩水活泼",
    description: "海边踩水超活泼！侧身笑着拍，浪花超美～",
    overlayUrl: genSVG(150),
    thumbnail: genSVG(150),
    voiceTip: "海边踩水超活泼！侧身笑着拍，浪花超美～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_191",
    name: "花卉市场浪漫",
    description: "花卉市场超浪漫！捧着一束花，笑着拍～",
    overlayUrl: genSVG(130),
    thumbnail: genSVG(130),
    voiceTip: "花卉市场超浪漫！捧着一束花，笑着拍～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_192",
    name: "厨房烹饪日常",
    description: "厨房里认真做饭超有生活感！侧拍超温馨～",
    overlayUrl: genSVG(055),
    thumbnail: genSVG(055),
    voiceTip: "厨房里认真做饭超有生活感！侧拍超温馨～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_193",
    name: "画室文艺创作",
    description: "画室里超有艺术气息！认真画画的样子超美～",
    overlayUrl: genSVG(070),
    thumbnail: genSVG(070),
    voiceTip: "画室里超有艺术气息！认真画画的样子超美～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_194",
    name: "阳台下午茶",
    description: "阳台下午茶超惬意！阳光洒进来，超有生活感～",
    overlayUrl: genSVG(040),
    thumbnail: genSVG(040),
    voiceTip: "阳台下午茶超惬意！阳光洒进来，超有生活感～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_195",
    name: "涂鸦墙街拍",
    description: "涂鸦墙前超酷！靠在墙边，歪头笑着拍～",
    overlayUrl: genSVG(145),
    thumbnail: genSVG(145),
    voiceTip: "涂鸦墙前超酷！靠在墙边，歪头笑着拍～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_196",
    name: "雨中撑伞浪漫",
    description: "雨天撑伞超有氛围感！让雨伞遮住半边脸，超神秘～",
    overlayUrl: genSVG(169),
    thumbnail: genSVG(169),
    voiceTip: "雨天撑伞超有氛围感！让雨伞遮住半边脸，超神秘～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_197",
    name: "滑板场活力",
    description: "滑板场超有活力！坐在场边笑着拍，超酷～",
    overlayUrl: genSVG(120),
    thumbnail: genSVG(120),
    voiceTip: "滑板场超有活力！坐在场边笑着拍，超酷～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_198",
    name: "便利店零食感",
    description: "便利店零食超可爱！拿一包零食笑着拍，超日常～",
    overlayUrl: genSVG(160),
    thumbnail: genSVG(160),
    voiceTip: "便利店零食超可爱！拿一包零食笑着拍，超日常～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_199",
    name: "屋顶派对夜色",
    description: "屋顶派对超嗨！夜晚灯光超有氛围，笑着拍～",
    overlayUrl: genSVG(100),
    thumbnail: genSVG(100),
    voiceTip: "屋顶派对超嗨！夜晚灯光超有氛围，笑着拍～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_200",
    name: "海边日落剪影",
    description: "海边日落剪影超浪漫！张开双臂，让轮廓发光～",
    overlayUrl: genSVG(150),
    thumbnail: genSVG(150),
    voiceTip: "海边日落剪影超浪漫！张开双臂，让轮廓发光～",
    category: "户外风景",
    version: 1,
  },
  // ========== 本次新增模板 201-230 ==========
  {
    id: "template_201",
    name: "露营篝火旁",
    description: "篝火旁超有氛围！靠近火光侧身站，脸被照得超暖～",
    overlayUrl: genSVG(1),
    thumbnail: genSVG(1),
    voiceTip: "篝火旁超有氛围！靠近火光侧身站，脸被照得超暖～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_202",
    name: "圣诞树前",
    description: "圣诞树前超有节日感！笑着看向镜头，背景要亮～",
    overlayUrl: genSVG(2),
    thumbnail: genSVG(2),
    voiceTip: "圣诞树前超有节日感！笑着看向镜头，背景要亮～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_203",
    name: "博物馆看展",
    description: "博物馆里超有文艺感！侧身站在艺术品旁，低头微笑～",
    overlayUrl: genSVG(3),
    thumbnail: genSVG(3),
    voiceTip: "博物馆里超有文艺感！侧身站在艺术品旁，低头微笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_204",
    name: "地铁站都市感",
    description: "地铁站冷调灯光超有都市感！靠着柱子随意自然～",
    overlayUrl: genSVG(4),
    thumbnail: genSVG(4),
    voiceTip: "地铁站冷调灯光超有都市感！靠着柱子随意自然～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_205",
    name: "便利店俏皮风",
    description: "便利店日常感满分！拿个零食饮料，俏皮地笑一个～",
    overlayUrl: genSVG(5),
    thumbnail: genSVG(5),
    voiceTip: "便利店日常感满分！拿个零食饮料，俏皮地笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_206",
    name: "健身房镜前",
    description: "健身房镜前超有活力！侧身站着，运动风满满～",
    overlayUrl: genSVG(6),
    thumbnail: genSVG(6),
    voiceTip: "健身房镜前超有活力！侧身站着，运动风满满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_207",
    name: "厨房烹饪",
    description: "厨房灶台前超温馨！端菜或举杯，笑得灿烂点～",
    overlayUrl: genSVG(7),
    thumbnail: genSVG(7),
    voiceTip: "厨房灶台前超温馨！端菜或举杯，笑得灿烂点～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_208",
    name: "温泉泡汤",
    description: "温泉蒸汽超治愈！靠在池边让蒸汽打在脸上，自然微笑～",
    overlayUrl: genSVG(8),
    thumbnail: genSVG(8),
    voiceTip: "温泉蒸汽超治愈！靠在池边让蒸汽打在脸上，自然微笑～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_209",
    name: "滑雪场酷照",
    description: "滑雪场运动感十足！站在雪道旁，墨镜酷酷的～",
    overlayUrl: genSVG(209),
    thumbnail: genSVG(209),
    voiceTip: "滑雪场运动感十足！站在雪道旁，墨镜酷酷的～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_210",
    name: "动物园长颈鹿",
    description: "长颈鹿背景超可爱！靠近围栏侧身站着，活泼自然～",
    overlayUrl: genSVG(10),
    thumbnail: genSVG(10),
    voiceTip: "长颈鹿背景超可爱！靠近围栏侧身站着，活泼自然～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_211",
    name: "公交站等车",
    description: "公交站日常感满满！靠着站牌看远方，文艺又自然～",
    overlayUrl: genSVG(11),
    thumbnail: genSVG(11),
    voiceTip: "公交站日常感满满！靠着站牌看远方，文艺又自然～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_212",
    name: "操场单杠",
    description: "操场运动风超阳光！站在单杠旁身体舒展，笑一个～",
    overlayUrl: genSVG(12),
    thumbnail: genSVG(12),
    voiceTip: "操场运动风超阳光！站在单杠旁身体舒展，笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_213",
    name: "音乐节舞台",
    description: "音乐节舞台超嗨！双手举起跟着节拍摇摆，表情夸张灿烂～",
    overlayUrl: genSVG(13),
    thumbnail: genSVG(13),
    voiceTip: "音乐节舞台超嗨！双手举起跟着节拍摇摆，表情夸张灿烂～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_214",
    name: "艺术展画廊",
    description: "画廊看展超文艺！站在艺术品旁侧头微笑，文艺感拉满～",
    overlayUrl: genSVG(14),
    thumbnail: genSVG(14),
    voiceTip: "画廊看展超文艺！站在艺术品旁侧头微笑，文艺感拉满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_215",
    name: "公园草坪野餐",
    description: "野餐垫上光线超温柔！坐在草地上，一手撑地侧头微笑～",
    overlayUrl: genSVG(15),
    thumbnail: genSVG(15),
    voiceTip: "野餐垫上光线超温柔！坐在草地上，一手撑地侧头微笑～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_216",
    name: "超市货架前",
    description: "超市货架前超有趣！拿个零食饮料，俏皮地看镜头笑～",
    overlayUrl: genSVG(16),
    thumbnail: genSVG(16),
    voiceTip: "超市货架前超有趣！拿个零食饮料，俏皮地看镜头笑～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_217",
    name: "便利店冰柜前",
    description: "便利店冰柜前光线冷白超清爽！拿瓶饮料俏皮地笑一个～",
    overlayUrl: genSVG(17),
    thumbnail: genSVG(17),
    voiceTip: "便利店冰柜前光线冷白超清爽！拿瓶饮料俏皮地笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_218",
    name: "地铁扶手电梯",
    description: "扶手电梯上光线冷调超有都市感！靠着扶手随意自然～",
    overlayUrl: genSVG(18),
    thumbnail: genSVG(18),
    voiceTip: "扶手电梯上光线冷调超有都市感！靠着扶手随意自然～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_219",
    name: "健身房器械区",
    description: "器械区背景好有运动感！侧身站着举起哑铃或笑着看镜头～",
    overlayUrl: genSVG(19),
    thumbnail: genSVG(19),
    voiceTip: "器械区背景好有运动感！侧身站着举起哑铃或笑着看镜头～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_220",
    name: "厨房水槽前",
    description: "水槽前光线均匀超好拍！端杯水或拿食材笑着看镜头～",
    overlayUrl: genSVG(20),
    thumbnail: genSVG(20),
    voiceTip: "水槽前光线均匀超好拍！端杯水或拿食材笑着看镜头～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_221",
    name: "草原牧场",
    description: "草原上光线超通透！站在草丛中笑着看向远方～",
    overlayUrl: genSVG(21),
    thumbnail: genSVG(21),
    voiceTip: "草原上光线超通透！站在草丛中笑着看向远方～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_222",
    name: "秋季落叶",
    description: "秋天落叶超有氛围！站在落叶中笑着拍一张～",
    overlayUrl: genSVG(22),
    thumbnail: genSVG(22),
    voiceTip: "秋天落叶超有氛围！站在落叶中笑着拍一张～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_223",
    name: "雾天户外",
    description: "雾天的光线超柔和！不用担心过曝，随便拍都好看～",
    overlayUrl: genSVG(23),
    thumbnail: genSVG(23),
    voiceTip: "雾天的光线超柔和！不用担心过曝，随便拍都好看～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_224",
    name: "楼梯间",
    description: "楼梯上光线从上往下打超有气场！侧身站着或坐在台阶上～",
    overlayUrl: genSVG(24),
    thumbnail: genSVG(24),
    voiceTip: "楼梯上光线从上往下打超有气场！侧身站着或坐在台阶上～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_225",
    name: "天台白天",
    description: "天台背景是城市天际线超有范儿！找个阴凉处侧身站着～",
    overlayUrl: genSVG(225),
    thumbnail: genSVG(225),
    voiceTip: "天台背景是城市天际线超有范儿！找个阴凉处侧身站着～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_226",
    name: "海边礁石",
    description: "礁石上有浪花超浪漫！站稳了侧身看向大海～",
    overlayUrl: genSVG(26),
    thumbnail: genSVG(26),
    voiceTip: "礁石上有浪花超浪漫！站稳了侧身看向大海～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_227",
    name: "灯笼夜景",
    description: "灯笼光暖暖的超有感觉！侧身站着让光打在侧脸上～",
    overlayUrl: genSVG(27),
    thumbnail: genSVG(27),
    voiceTip: "灯笼光暖暖的超有感觉！侧身站着让光打在侧脸上～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_228",
    name: "水族馆",
    description: "水族馆光线超梦幻！站在大鱼缸前笑着看向镜头～",
    overlayUrl: genSVG(28),
    thumbnail: genSVG(28),
    voiceTip: "水族馆光线超梦幻！站在大鱼缸前笑着看向镜头～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_229",
    name: "摩天轮",
    description: "摩天轮里光线超柔和！侧身坐着看向窗外，笑一个～",
    overlayUrl: genSVG(29),
    thumbnail: genSVG(29),
    voiceTip: "摩天轮里光线超柔和！侧身坐着看向窗外，笑一个～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_230",
    name: "教堂婚礼",
    description: "教堂背景超庄严！端正站着笑得温柔点，背景要拍完整～",
    overlayUrl: genSVG(30),
    thumbnail: genSVG(30),
    voiceTip: "教堂背景超庄严！端正站着笑得温柔点，背景要拍完整～",
    category: "特殊风格",
    version: 1,
  },
  // ========== Round 25 新增模板 (231-250) ==========
  {
    id: "template_231",
    name: "复古唱片店",
    description: "唱片店内文艺感十足！靠在唱片架旁，假装在选唱片，自然又有氛围～",
    overlayUrl: genSVG(10),
    thumbnail: genSVG(10),
    voiceTip: "唱片店超有文艺感！靠在唱片架旁假装选唱片，自然又文艺～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_232",
    name: "自行车骑行",
    description: "骑自行车时抓拍动态瞬间，活力感十足！",
    overlayUrl: genSVG(8),
    thumbnail: genSVG(8),
    voiceTip: "骑自行车时抓拍！身体前倾，眼睛看镜头，活力满满的笑容～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_233",
    name: "便利店货架前",
    description: "便利店货架前拿零食饮料互动，俏皮可爱的日常感！",
    overlayUrl: genSVG(15),
    thumbnail: genSVG(15),
    voiceTip: "拿个零食饮料互动！俏皮地看镜头，生活感十足～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_234",
    name: "水族馆大鱼缸",
    description: "水族馆大鱼缸前侧脸站立，蓝色水光打在脸上超梦幻！",
    overlayUrl: genSVG(20),
    thumbnail: genSVG(20),
    voiceTip: "侧脸站在大鱼缸前！蓝色水光打在脸上，超梦幻～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_235",
    name: "音乐节舞台侧",
    description: "音乐节跟着节奏摇摆，表情夸张灿烂的时候抓拍！",
    overlayUrl: genSVG(235),
    thumbnail: genSVG(235),
    voiceTip: "跟着节拍摇摆！表情夸张灿烂的时候按下快门，活力十足！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_236",
    name: "酒吧靠吧台",
    description: "酒吧暖光下靠在吧台边，鸡尾酒杯做道具，氛围感拉满！",
    overlayUrl: genSVG(12),
    thumbnail: genSVG(12),
    voiceTip: "靠在吧台边！拿着鸡尾酒杯，笑着看镜头，氛围感绝了～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_237",
    name: "花卉市场捧花",
    description: "花卉市场捧一束鲜花互动，蹲下来仰拍人在花丛中美美的～",
    overlayUrl: genSVG(5),
    thumbnail: genSVG(5),
    voiceTip: "捧一束花互动！蹲下来仰拍，人在花丛中美美的～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_238",
    name: "游乐场碰碰车",
    description: "碰碰车场地灯光超有动感！笑着抓拍活力瞬间～",
    overlayUrl: genSVG(8),
    thumbnail: genSVG(8),
    voiceTip: "开着碰碰车笑着看镜头！动态抓拍活力十足～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_239",
    name: "电影院海报前",
    description: "电影院走廊站在海报旁，和海报互动超有感觉！",
    overlayUrl: genSVG(18),
    thumbnail: genSVG(18),
    voiceTip: "站在电影海报旁！侧身站着和海报互动，超有感觉～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_240",
    name: "图书馆书架间",
    description: "图书馆书架间安静站立，低头看书或看镜头都超美！",
    overlayUrl: genSVG(2),
    thumbnail: genSVG(2),
    voiceTip: "靠在书架旁！假装在看书或看镜头，安静的美感～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_241",
    name: "健身房器械区",
    description: "健身房器械区侧身站立，运动风满满，活力十足！",
    overlayUrl: genSVG(22),
    thumbnail: genSVG(22),
    voiceTip: "侧身站在器械旁！举起哑铃或空手笑着看镜头，运动风满满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_242",
    name: "超市零食货架",
    description: "超市零食货架前拿商品互动，俏皮可爱的购物日常！",
    overlayUrl: genSVG(16),
    thumbnail: genSVG(16),
    voiceTip: "拿零食饮料互动！俏皮地看镜头，购物日常感满满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_243",
    name: "冰淇淋店甜品台",
    description: "冰淇淋店甜品台前拿着冰淇淋，俏皮可爱超有夏天气息～",
    overlayUrl: genSVG(5),
    thumbnail: genSVG(5),
    voiceTip: "捧着冰淇淋！俏皮地笑一个，夏天气息满满～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_244",
    name: "便利店冰柜前",
    description: "便利店冰柜前拿瓶饮料，冷白灯光下也超有活力！",
    overlayUrl: genSVG(15),
    thumbnail: genSVG(15),
    voiceTip: "拿瓶饮料站在冰柜前！笑着看镜头，活力满满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_245",
    name: "水族馆隧道",
    description: "水族馆隧道里仰头看鱼群，蓝色光影超梦幻！",
    overlayUrl: genSVG(20),
    thumbnail: genSVG(20),
    voiceTip: "仰头看鱼群！让蓝色光影打在脸上，超梦幻～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_246",
    name: "游乐园旋转木马",
    description: "旋转木马超有童话感！坐着或靠着木马，活泼可爱～",
    overlayUrl: genSVG(246),
    thumbnail: genSVG(246),
    voiceTip: "靠在旋转木马上！活泼可爱，笑着看镜头抓拍～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_247",
    name: "电影院爆米花",
    description: "捧着爆米花和饮料，俏皮地看镜头，生活感十足～",
    overlayUrl: genSVG(12),
    thumbnail: genSVG(12),
    voiceTip: "捧着爆米花！俏皮地笑一个，生活感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_248",
    name: "书店阅读角",
    description: "书店阅读角安静坐着，手拿书本，文艺感满满～",
    overlayUrl: genSVG(2),
    thumbnail: genSVG(2),
    voiceTip: "坐在阅读角拿本书！安静看书或抬头微笑，文艺感拉满～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_249",
    name: "花卉拱门下",
    description: "花卉拱门下站立，超浪漫的户外拍照背景！",
    overlayUrl: genSVG(249),
    thumbnail: genSVG(249),
    voiceTip: "站在花卉拱门下！侧身微笑，背景超浪漫～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_250",
    name: "演唱会荧光棒",
    description: "演唱会现场拿着荧光棒，跟着节拍摇摆，氛围感爆棚！",
    overlayUrl: genSVG(250),
    thumbnail: genSVG(250),
    voiceTip: "举着荧光棒跟着节拍摇摆！表情灿烂的时候按下快门！",
    category: "特殊风格",
    version: 1,
  },
  // ========== Round 27 新增模板 251-254 ==========
  {
    id: "template_251",
    description: "星空露营超浪漫！躺在帐篷里仰拍，星空做背景超梦幻～",
    overlayUrl: genSVG(251),
    thumbnail: genSVG(251),
    voiceTip: "躺在帐篷里仰拍，星空做背景超梦幻～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_252",
    description: "泳池日光超有夏威夷感！泳池边阳光充足，侧身站着笑一个～",
    overlayUrl: genSVG(252),
    thumbnail: genSVG(252),
    voiceTip: "泳池边阳光充足，侧身站着笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_253",
    description: "竹林禅意超有感觉！竹林小径光线斑驳，走着抓拍超有感觉～",
    overlayUrl: genSVG(253),
    thumbnail: genSVG(253),
    voiceTip: "竹林小径光线斑驳，走着抓拍超有感觉～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_254",
    description: "天台黄昏光线超美！侧身站着让光打在侧脸上，氛围感绝了～",
    overlayUrl: genSVG(254),
    thumbnail: genSVG(254),
    voiceTip: "天台黄昏光线超美，侧身站着让光打在侧脸上～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_255",
    name: "花海漫步",
    description: "花海里漫步，超浪漫的春日人像",
    overlayUrl: genSVG(255),
    thumbnail: genSVG(255),
    voiceTip: "在花海中慢慢走，转身回眸，超浪漫～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_256",
    name: "草原骑马",
    description: "草原骑马超有自由感，大片感十足",
    overlayUrl: genSVG(256),
    thumbnail: genSVG(256),
    voiceTip: "骑在马上或者站在马旁，笑着看向远方～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_257",
    name: "海边礁石",
    description: "礁石上海浪拍打，超有电影感",
    overlayUrl: genSVG(257),
    thumbnail: genSVG(257),
    voiceTip: "站在礁石上，侧身看向大海，让海浪声成为背景～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_258",
    name: "山坡野餐",
    description: "山坡上野餐超有春日感，背景是城市天际线",
    overlayUrl: genSVG(258),
    thumbnail: genSVG(258),
    voiceTip: "坐在野餐垫上，一手撑地，看向远方笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_259",
    name: "向日葵田",
    description: "向日葵金黄一片，超有夏日的活力感",
    overlayUrl: genSVG(259),
    thumbnail: genSVG(259),
    voiceTip: "站在向日葵花丛里，抬头看花或低头微笑～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_260",
    name: "芦苇荡",
    description: "芦苇荡里超有秋日感，夕阳下的剪影超美",
    overlayUrl: genSVG(260),
    thumbnail: genSVG(260),
    voiceTip: "站在芦苇丛中，侧身看向远方，让风吹起芦苇～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_261",
    name: "梯田风光",
    description: "梯田层层叠叠，超有大地艺术感",
    overlayUrl: genSVG(261),
    thumbnail: genSVG(261),
    voiceTip: "站在梯田边，侧身看向远方，背景超有层次～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_262",
    name: "红土地",
    description: "红土地超有云南风情，色彩浓烈超上镜",
    overlayUrl: genSVG(262),
    thumbnail: genSVG(262),
    voiceTip: "站在红土地上，侧身看向镜头，背景超有异域感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_263",
    name: "海边灯塔",
    description: "灯塔背景超有画面感，电影感拉满",
    overlayUrl: genSVG(263),
    thumbnail: genSVG(263),
    voiceTip: "站在灯塔下或旁边，侧身回头看向镜头～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_264",
    name: "悬崖海边",
    description: "悬崖俯瞰大海，超有大片感，气势磅礴",
    overlayUrl: genSVG(264),
    thumbnail: genSVG(264),
    voiceTip: "站在悬崖边，背对大海，看向镜头笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_265",
    name: "湖泊倒影",
    description: "湖面如镜超宁静，倒影和人都完美",
    overlayUrl: genSVG(265),
    thumbnail: genSVG(265),
    voiceTip: "站在湖边，低头看水面或看向远方，超宁静～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_266",
    name: "溪流抓拍",
    description: "溪流边光线斑驳，超有小清新感",
    overlayUrl: genSVG(266),
    thumbnail: genSVG(266),
    voiceTip: "站在溪边，让水流声成为背景，自然微笑看向镜头～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_267",
    name: "山顶远眺",
    description: "山顶俯瞰城市或山峦，超有诗和远方感",
    overlayUrl: genSVG(267),
    thumbnail: genSVG(267),
    voiceTip: "站在山顶，背对城市或山峦，看向远方超有诗意～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_268",
    name: "沙漠驼队",
    description: "沙漠里驼队超有丝绸之路感，大漠风情",
    overlayUrl: genSVG(268),
    thumbnail: genSVG(268),
    voiceTip: "站在沙漠中，背对驼队，看向镜头笑一个～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_269",
    name: "枫叶林",
    description: "枫叶林红黄一片，秋日感拉满",
    overlayUrl: genSVG(269),
    thumbnail: genSVG(269),
    voiceTip: "站在枫叶林里，抬头看红叶或侧头微笑，秋日感十足～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_270",
    name: "竹林深处",
    description: "竹林深处光线斑驳，超有禅意",
    overlayUrl: genSVG(270),
    thumbnail: genSVG(270),
    voiceTip: "走在竹林里，让斑驳的光影打在脸上，超有禅意～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_271",
    name: "地铁站艺术墙",
    description: "地铁站艺术墙超有设计感，文艺感拉满",
    overlayUrl: genSVG(271),
    thumbnail: genSVG(271),
    voiceTip: "站在艺术墙前，侧身看向镜头，文艺感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_272",
    name: "便利店橱窗",
    description: "便利店橱窗灯光亮丽，夜晚超有都市感",
    overlayUrl: genSVG(272),
    thumbnail: genSVG(272),
    voiceTip: "站在便利店橱窗前，让灯光打在脸上，超有都市感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_273",
    name: "天桥俯拍",
    description: "天桥上俯拍街道，都市感十足",
    overlayUrl: genSVG(273),
    thumbnail: genSVG(273),
    voiceTip: "站在天桥上，俯拍街道，看向镜头笑一个～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_274",
    name: "红绿灯路口",
    description: "红绿灯路口超有都市感，霓虹灯下超酷",
    overlayUrl: genSVG(274),
    thumbnail: genSVG(274),
    voiceTip: "站在路口等灯，侧身看向镜头，超有都市感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_275",
    name: "商场扶梯",
    description: "商场自动扶梯超有都市节奏感",
    overlayUrl: genSVG(275),
    thumbnail: genSVG(275),
    voiceTip: "站在扶梯上，自然地看向镜头，超有节奏感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_276",
    name: "地下通道",
    description: "地下通道光线有明暗对比，超有电影感",
    overlayUrl: genSVG(276),
    thumbnail: genSVG(276),
    voiceTip: "站在地下通道光影交界处，侧身看向镜头～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_277",
    name: "街边电话亭",
    description: "英伦风电话亭超有异国感，拍照超有范儿",
    overlayUrl: genSVG(277),
    thumbnail: genSVG(277),
    voiceTip: "站在电话亭旁边，侧身回头看向镜头～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_278",
    name: "涂鸦墙",
    description: "彩色涂鸦墙超有街头艺术感，酷感十足",
    overlayUrl: genSVG(278),
    thumbnail: genSVG(278),
    voiceTip: "靠在涂鸦墙前，酷酷地看向镜头，街头感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_279",
    name: "地铁末班",
    description: "深夜地铁站人少超有孤独感，电影感拉满",
    overlayUrl: genSVG(279),
    thumbnail: genSVG(279),
    voiceTip: "站在空旷的地铁站台，看向远方，电影感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_280",
    name: "旋转门",
    description: "酒店旋转门超有都市感，大堂感十足",
    overlayUrl: genSVG(280),
    thumbnail: genSVG(280),
    voiceTip: "站在旋转门旁边，侧身看向镜头，都市感满满～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_281",
    name: "摩天大楼",
    description: "摩天大楼脚下超有压迫感，大片感",
    overlayUrl: genSVG(281),
    thumbnail: genSVG(281),
    voiceTip: "站在大楼脚下，仰头看向镜头，超有冲击力～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_282",
    name: "公交站牌",
    description: "公交站牌超有都市通勤感，日常又好看",
    overlayUrl: genSVG(282),
    thumbnail: genSVG(282),
    voiceTip: "站在公交站牌下，靠着站牌看向镜头～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_283",
    name: "地下车库",
    description: "地下车库线条感强，工业风超酷",
    overlayUrl: genSVG(283),
    thumbnail: genSVG(283),
    voiceTip: "站在车库线条前，侧身看向镜头，工业风十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_284",
    name: "天桥仰拍",
    description: "天桥下仰拍超有纵深感，都市感拉满",
    overlayUrl: genSVG(284),
    thumbnail: genSVG(284),
    voiceTip: "站在天桥下，仰头看向镜头，纵深感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_285",
    name: "街头艺人",
    description: "街头艺人表演背景超有文艺感",
    overlayUrl: genSVG(285),
    thumbnail: genSVG(285),
    voiceTip: "站在街头艺人旁边，看向镜头，文艺感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_286",
    name: "厨房料理台",
    description: "厨房料理台光线均匀，做饭日常感满满",
    overlayUrl: genSVG(286),
    thumbnail: genSVG(286),
    voiceTip: "站在料理台前，手里拿着食材，笑着看向镜头～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_287",
    name: "浴室镜前",
    description: "浴室镜前光线超均匀，自拍超显气质",
    overlayUrl: genSVG(287),
    thumbnail: genSVG(287),
    voiceTip: "对着镜子站好，侧身45度，笑一个～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_288",
    name: "阳台躺椅",
    description: "阳台躺椅超有慵懒感，夏日午后必备",
    overlayUrl: genSVG(288),
    thumbnail: genSVG(288),
    voiceTip: "躺在阳台躺椅上，一只手撑着，看向镜头笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_289",
    name: "客厅沙发",
    description: "客厅沙发超有居家感，慵懒又好看",
    overlayUrl: genSVG(289),
    thumbnail: genSVG(289),
    voiceTip: "靠在沙发上，一只手托着脸，看向镜头笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_290",
    name: "书架前阅读",
    description: "书架前看书超有文艺感，文静气质满满",
    overlayUrl: genSVG(290),
    thumbnail: genSVG(290),
    voiceTip: "站在书架前，随手拿本书，低头看书或抬头微笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_291",
    name: "餐桌前美食",
    description: "餐桌前美食超有生活感，温馨又好看",
    overlayUrl: genSVG(291),
    thumbnail: genSVG(291),
    voiceTip: "坐在餐桌前，手捧餐具，看向镜头笑一个～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_292",
    name: "钢琴前",
    description: "钢琴前超有艺术气质，文艺感拉满",
    overlayUrl: genSVG(292),
    thumbnail: genSVG(292),
    voiceTip: "坐在钢琴前，手放在琴键上，笑着看向镜头～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_293",
    name: "落地窗前",
    description: "落地窗前光线超美，背光侧脸都好看",
    overlayUrl: genSVG(293),
    thumbnail: genSVG(293),
    voiceTip: "站在落地窗前，让光线从身后透进来，侧身看向镜头～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_294",
    name: "复古装修",
    description: "复古装修超有年代感，穿越感十足",
    overlayUrl: genSVG(294),
    thumbnail: genSVG(294),
    voiceTip: "站在复古家具旁，侧身看向镜头，年代感十足～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_295",
    name: "床铺清晨",
    description: "床铺清晨光线柔和，超有慵懒美感",
    overlayUrl: genSVG(295),
    thumbnail: genSVG(295),
    voiceTip: "靠在床头，一只手撑着脸，看向镜头笑一个～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_296",
    name: "复古胶片",
    description: "复古胶片感超有年代感，穿越时光的美",
    overlayUrl: genSVG(296),
    thumbnail: genSVG(296),
    voiceTip: "穿上复古服装，侧身看向镜头，胶片感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_297",
    name: "韩系清新",
    description: "韩系清新超有氧气感，温柔又好看",
    overlayUrl: genSVG(297),
    thumbnail: genSVG(297),
    voiceTip: "穿着简约，侧身看向镜头，氧气感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_298",
    name: "日系杂志",
    description: "日系杂志感超有文艺感，杂志大片风",
    overlayUrl: genSVG(298),
    thumbnail: genSVG(298),
    voiceTip: "穿着日式服装，侧身看向镜头，杂志感满满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_299",
    name: "法式优雅",
    description: "法式优雅超有高级感，浪漫又好看",
    overlayUrl: genSVG(299),
    thumbnail: genSVG(299),
    voiceTip: "穿着法式连衣裙，侧身看向镜头，高级感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_300",
    name: "运动活力",
    description: "运动装活力满满，超有健康美感",
    overlayUrl: genSVG(300),
    thumbnail: genSVG(300),
    voiceTip: "穿着运动装，比个耶或举过头顶，笑得灿烂～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_301",
    name: "古风汉服",
    description: "古风汉服超有东方美，气质满满",
    overlayUrl: genSVG(301),
    thumbnail: genSVG(301),
    voiceTip: "穿着汉服，侧身看向镜头，古风感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_302",
    name: "甜美公主",
    description: "甜美公主风超有少女感，梦幻又好看",
    overlayUrl: genSVG(302),
    thumbnail: genSVG(302),
    voiceTip: "穿着甜美公主裙，侧头微笑，少女感满满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_303",
    name: "帅气中性",
    description: "帅气中性风超有态度，酷感十足",
    overlayUrl: genSVG(303),
    thumbnail: genSVG(303),
    voiceTip: "穿着中性服装，酷酷地看向镜头，超有态度～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_304",
    name: "海边度假",
    description: "海边度假超有夏日感，沙滩海风超浪漫",
    overlayUrl: genSVG(304),
    thumbnail: genSVG(304),
    voiceTip: "穿着度假风，站在海边，让海风吹起头发～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_305",
    name: "都市通勤",
    description: "都市通勤风超有职业感，干练又好看",
    overlayUrl: genSVG(305),
    thumbnail: genSVG(305),
    voiceTip: "穿着通勤装，站在写字楼前，干练感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_306",
    name: "拥抱对视",
    description: "两人相拥对视，超甜的情侣瞬间",
    overlayUrl: genSVG(306),
    thumbnail: genSVG(306),
    voiceTip: "两人面对面，抱在一起，看着对方笑～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_307",
    name: "牵手背影",
    description: "两人牵手背影超有氛围感，简约又甜蜜",
    overlayUrl: genSVG(307),
    thumbnail: genSVG(307),
    voiceTip: "两人背对镜头，手牵手站好，头微微侧一点～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_308",
    name: "额头碰额头",
    description: "额头碰额头超甜，亲密感拉满",
    overlayUrl: genSVG(308),
    thumbnail: genSVG(308),
    voiceTip: "两人额头轻轻碰在一起，笑着看向镜头～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_309",
    name: "背后环抱自拍",
    description: "男生从后面环抱自拍，甜蜜感溢出屏幕",
    overlayUrl: genSVG(309),
    thumbnail: genSVG(309),
    voiceTip: "女生站着，男生从后面抱住，一起看向镜头笑～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_310",
    name: "举高高",
    description: "男生把女生举高高，超有活力感",
    overlayUrl: genSVG(310),
    thumbnail: genSVG(310),
    voiceTip: "男生把女生举起来，笑着看向镜头，活力满满～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_311",
    name: "一起做饭",
    description: "两人一起做饭超有生活感，甜蜜又温馨",
    overlayUrl: genSVG(311),
    thumbnail: genSVG(311),
    voiceTip: "两人在厨房里，一起看着镜头笑～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_312",
    name: "牵手过马路",
    description: "两人牵手过马路超有都市感，温馨日常",
    overlayUrl: genSVG(312),
    thumbnail: genSVG(312),
    voiceTip: "两人手牵手，侧身看向镜头，温馨日常感～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_313",
    name: "一起看日落",
    description: "两人一起看日落超浪漫，夕阳超美",
    overlayUrl: genSVG(313),
    thumbnail: genSVG(313),
    voiceTip: "两人背对夕阳，侧身看向镜头，夕阳在身后超浪漫～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_314",
    name: "比心合照",
    description: "情侣比心超可爱，甜蜜感拉满",
    overlayUrl: genSVG(314),
    thumbnail: genSVG(314),
    voiceTip: "两人一起用手比个心，笑着看向镜头～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_315",
    name: "偷亲瞬间",
    description: "假装亲一下超甜蜜，抓拍瞬间绝了",
    overlayUrl: genSVG(315),
    thumbnail: genSVG(315),
    voiceTip: "假装亲一下对方的侧脸，这个瞬间绝了～",
    category: "情侣合照",
    version: 1,
  },
  {
    id: "template_316",
    name: "咖啡馆角落",
    description: "咖啡馆角落超有小资情调，捧着咖啡超好看",
    overlayUrl: genSVG(316),
    thumbnail: genSVG(316),
    voiceTip: "捧一杯咖啡，坐在角落，看向窗外或镜头～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_317",
    name: "火锅热气",
    description: "火锅前热气腾腾，生活感满满",
    overlayUrl: genSVG(317),
    thumbnail: genSVG(317),
    voiceTip: "对着火锅举筷子，让热气模糊一点点脸庞，氛围感拉满！",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_318",
    name: "甜品店",
    description: "甜品店里光线柔和，捧着甜点超可爱",
    overlayUrl: genSVG(318),
    thumbnail: genSVG(318),
    voiceTip: "捧着甜品，侧头微笑，甜品感十足～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_319",
    name: "酒吧吧台",
    description: "酒吧吧台灯光超有氛围感，霓虹灯下超酷",
    overlayUrl: genSVG(319),
    thumbnail: genSVG(319),
    voiceTip: "靠在吧台边，让灯光打在侧脸上，超有氛围～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_320",
    name: "路边小吃摊",
    description: "路边小吃摊烟火气超足，超有生活感",
    overlayUrl: genSVG(320),
    thumbnail: genSVG(320),
    voiceTip: "拿着路边小吃，俏皮地看向镜头，烟火气十足～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_321",
    name: "奶茶店",
    description: "奶茶店里光线均匀，捧着奶茶超可爱",
    overlayUrl: genSVG(321),
    thumbnail: genSVG(321),
    voiceTip: "捧一杯奶茶，侧头微笑，奶茶感十足～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_322",
    name: "面包店",
    description: "面包店暖光超温馨，捧着面包超有食欲",
    overlayUrl: genSVG(322),
    thumbnail: genSVG(322),
    voiceTip: "捧着新鲜面包，侧头微笑，暖光感十足～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_323",
    name: "西餐厅",
    description: "西餐厅装修典雅，烛光超有仪式感",
    overlayUrl: genSVG(323),
    thumbnail: genSVG(323),
    voiceTip: "坐在西餐位，举起酒杯，笑着看向镜头～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_324",
    name: "日料店",
    description: "日料店装修简约清新，超有日式感",
    overlayUrl: genSVG(324),
    thumbnail: genSVG(324),
    voiceTip: "坐在日料台前，手拿寿司，看向镜头笑一个～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_325",
    name: "下午茶三层架",
    description: "下午茶三层架超有英伦感，优雅又好看",
    overlayUrl: genSVG(325),
    thumbnail: genSVG(325),
    voiceTip: "坐在桌前，手捧茶杯，看向镜头优雅微笑～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_326",
    name: "框中框构图",
    description: "找门框窗框当框架，主体在框中超有层次",
    overlayUrl: genSVG(326),
    thumbnail: genSVG(326),
    voiceTip: "站在门框或窗框里，让框作为前景，层次感十足～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_327",
    name: "镜像对称构图",
    description: "找镜面或水面利用对称反射，增加层次感",
    overlayUrl: genSVG(327),
    thumbnail: genSVG(327),
    voiceTip: "站在镜面前，让反射进入画面，对称又梦幻～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_328",
    name: "引导线构图",
    description: "找道路或栏杆做引导线，构图超有纵深感",
    overlayUrl: genSVG(328),
    thumbnail: genSVG(328),
    voiceTip: "站在有引导线的场景里，顺着线看向镜头，纵深感十足～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_329",
    name: "留白构图",
    description: "背景留白超有呼吸感，高级又好看",
    overlayUrl: genSVG(329),
    thumbnail: genSVG(329),
    voiceTip: "让人站在画面一侧，另一侧大量留白，高级感十足～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_330",
    name: "三角构图",
    description: "身体形成三角形，超稳又有动感",
    overlayUrl: genSVG(330),
    thumbnail: genSVG(330),
    voiceTip: "身体稍微侧一下，形成三角形构图，超有气场～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_331",
    name: "S形构图",
    description: "身体形成S形曲线，超有女性柔美感",
    overlayUrl: genSVG(331),
    thumbnail: genSVG(331),
    voiceTip: "站立时身体稍微弯曲成S形，超有柔美感～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_332",
    name: "C形构图",
    description: "身体形成C形曲线，优雅又自然",
    overlayUrl: genSVG(332),
    thumbnail: genSVG(332),
    voiceTip: "身体稍微弯曲成C形，超有优雅感～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_333",
    name: "对角线构图",
    description: "身体倾斜成对角线，超有动感",
    overlayUrl: genSVG(333),
    thumbnail: genSVG(333),
    voiceTip: "稍微倾斜身体，顺着对角线看向镜头，动感十足～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_334",
    name: "前景虚化",
    description: "找树叶或花朵做前景虚化，层次感丰富",
    overlayUrl: genSVG(334),
    thumbnail: genSVG(334),
    voiceTip: "让前景虚化挡住一部分脸，画面层次更丰富～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_335",
    name: "框架前景",
    description: "用门框窗框做前景，构图超有电影感",
    overlayUrl: genSVG(335),
    thumbnail: genSVG(335),
    voiceTip: "站在门框或窗框前，让框作为前景，电影感十足～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_336",
    name: "地平线偏移",
    description: "地平线偏移构图，打破平淡感",
    overlayUrl: genSVG(336),
    thumbnail: genSVG(336),
    voiceTip: "让地平线偏到画面一侧，打破平淡，构图更有张力～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_337",
    name: "局部特写",
    description: "只拍局部特写，超有艺术感",
    overlayUrl: genSVG(337),
    thumbnail: genSVG(337),
    voiceTip: "让男友只拍局部，比如侧脸+锁骨，特写超有艺术感～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_338",
    name: "剪影特写",
    description: "逆光剪影超有意境感",
    overlayUrl: genSVG(338),
    thumbnail: genSVG(338),
    voiceTip: "背对光源，让轮廓形成剪影，超有意境～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_339",
    name: "高低机位",
    description: "高低机位变化构图丰富多样",
    overlayUrl: genSVG(339),
    thumbnail: genSVG(339),
    voiceTip: "让男友尝试高机位俯拍和低机位仰拍，都超有感觉～",
    category: "构图技巧",
    version: 1,
  },
  {
    id: "template_340",
    name: "三分法进阶",
    description: "人脸放在三分点，构图专业又好看",
    overlayUrl: genSVG(340),
    thumbnail: genSVG(340),
    voiceTip: "打开九宫格，把人脸放在交叉点上，构图立刻变专业～",
    category: "构图技巧",
    version: 1,
  },
  // ========== Round 32 新增模板 341-360 ==========
  {
    id: "template_341",
    name: "车窗回眸",
    description: "侧身坐车，回眸看镜头，自然又灵动",
    overlayUrl: genSVG(341),
    thumbnail: genSVG(341),
    voiceTip: "坐在车窗边，侧身回头看我，微笑～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_342",
    name: "天台仰头",
    description: "仰头看向天空，背景是城市天际线",
    overlayUrl: genSVG(342),
    thumbnail: genSVG(342),
    voiceTip: "仰头看天空，背景是天际线，超有氛围感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_343",
    name: "樱花雨特写",
    description: "樱花飘落时抬头微笑，捕捉灵动瞬间",
    overlayUrl: genSVG(343),
    thumbnail: genSVG(343),
    voiceTip: "樱花飘落时抬头，让花瓣落在脸上，自然微笑～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_344",
    name: "银杏金秋",
    description: "站在金黄银杏树下，秋日感拉满",
    overlayUrl: genSVG(344),
    thumbnail: genSVG(344),
    voiceTip: "站在银杏树下，抬眼看镜头，秋日感十足～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_345",
    name: "露营篝火",
    description: "围坐篝火旁，火光打在脸上超温暖",
    overlayUrl: genSVG(345),
    thumbnail: genSVG(345),
    voiceTip: "围坐篝火旁，让火光打在侧脸上，温暖又浪漫～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_346",
    name: "滑雪动感",
    description: "滑雪服穿搭抓拍，活力满满",
    overlayUrl: genSVG(346),
    thumbnail: genSVG(346),
    voiceTip: "滑雪服穿着，笑着比个耶，活力满满！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_347",
    name: "便利店俏皮",
    description: "拿零食饮料当道具，俏皮可爱",
    overlayUrl: genSVG(347),
    thumbnail: genSVG(347),
    voiceTip: "拿个零食饮料，对着镜头俏皮地笑～",
    category: "室内场景",
    version: 1,
  },
  {
    id: "template_348",
    name: "健身房活力",
    description: "运动装备出镜，活力动感抓拍",
    overlayUrl: genSVG(348),
    thumbnail: genSVG(348),
    voiceTip: "穿运动装，笑着举起哑铃或拉伸，活力满满！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_349",
    name: "古镇老街",
    description: "古镇老街背景，文艺又有年代感",
    overlayUrl: genSVG(349),
    thumbnail: genSVG(349),
    voiceTip: "靠在老墙边，侧头微笑，文艺感十足～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_350",
    name: "公交站日常",
    description: "公交站台日常感，文艺抓拍",
    overlayUrl: genSVG(350),
    thumbnail: genSVG(350),
    voiceTip: "靠在公交站牌旁，看向远方，自然文艺～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_351",
    name: "水族馆梦幻",
    description: "水族馆大鱼缸前，蓝色梦幻感",
    overlayUrl: genSVG(351),
    thumbnail: genSVG(351),
    voiceTip: "站在大鱼缸前，让蓝色光打在脸上，超梦幻～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_352",
    name: "音乐节现场",
    description: "音乐节舞台感，活力动感",
    overlayUrl: genSVG(352),
    thumbnail: genSVG(352),
    voiceTip: "跟着节拍摇摆，双手举起，表情夸张灿烂！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_353",
    name: "圣诞树前",
    description: "圣诞树前节日感，温暖又喜庆",
    overlayUrl: genSVG(353),
    thumbnail: genSVG(353),
    voiceTip: "站在圣诞树旁，笑着看镜头，节日氛围感拉满～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_354",
    name: "烘焙坊甜点",
    description: "捧着面包或甜点，暖黄色调超温馨",
    overlayUrl: genSVG(354),
    thumbnail: genSVG(354),
    voiceTip: "捧着甜点，侧头微笑，暖黄色调超有感觉～",
    category: "餐厅美食",
    version: 1,
  },
  {
    id: "template_355",
    name: "草原骑马",
    description: "草原骑马帅气瞬间，马背上活力抓拍",
    overlayUrl: genSVG(355),
    thumbnail: genSVG(355),
    voiceTip: "骑在马上，笑着看镜头，帅气又活力～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_356",
    name: "寺庙祈福",
    description: "寺庙古建筑前，传统文化感",
    overlayUrl: genSVG(356),
    thumbnail: genSVG(356),
    voiceTip: "站在寺庙建筑前，侧身微笑，文艺又有文化感～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_357",
    name: "高铁车窗",
    description: "高铁靠窗座位，旅途感十足",
    overlayUrl: genSVG(357),
    thumbnail: genSVG(357),
    voiceTip: "靠在高铁车窗边，看向窗外，旅途感十足～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_358",
    name: "雕塑前艺术感",
    description: "城市雕塑前，文艺艺术感",
    overlayUrl: genSVG(358),
    thumbnail: genSVG(358),
    voiceTip: "站在雕塑旁边，笑着看镜头，文艺艺术感～",
    category: "城市街拍",
    version: 1,
  },
  {
    id: "template_359",
    name: "毕业典礼",
    description: "毕业礼服学位帽，青春感十足",
    overlayUrl: genSVG(359),
    thumbnail: genSVG(359),
    voiceTip: "戴着学位帽，把帽子稍微抬高露出额头，笑一个！",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_360",
    name: "摩天轮包厢",
    description: "摩天轮包厢内，城市全景背景",
    overlayUrl: genSVG(360),
    thumbnail: genSVG(360),
    voiceTip: "坐在摩天轮里，看向窗外或看镜头，浪漫感十足～",
    category: "户外风景",
    version: 1,
  },
  // ========== Round 35 新增 25 个模板 ==========
  {
    id: "template_361",
    name: "艺术装置展",
    description: "艺术馆内创意装置艺术背景",
    overlayUrl: genSVG(361),
    thumbnail: genSVG(361),
    voiceTip: "艺术装置前超有氛围！随意站着，和艺术品互动一下～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_362",
    name: "瑜伽修炼",
    description: "室内瑜伽垫或户外草地上做瑜伽",
    overlayUrl: genSVG(362),
    thumbnail: genSVG(362),
    voiceTip: "瑜伽姿势舒展超美！侧身站着或坐着，阳光洒下来绝了～",
    category: "运动健身",
    version: 1,
  },
  {
    id: "template_363",
    name: "农场采摘",
    description: "水果农场采摘新鲜水果",
    overlayUrl: genSVG(363),
    thumbnail: genSVG(363),
    voiceTip: "捧着刚摘的水果，笑一个！田园感满满～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_364",
    name: "温泉泡汤",
    description: "日式温泉或泡汤场景背景",
    overlayUrl: genSVG(364),
    thumbnail: genSVG(364),
    voiceTip: "温泉蒸汽缭绕超有氛围！让脸稍微靠近光源～",
    category: "特殊风格",
    version: 1,
  },
  {
    id: "template_365",
    name: "冰场舞动",
    description: "室内滑冰场或冰壶馆",
    overlayUrl: genSVG(365),
    thumbnail: genSVG(365),
    voiceTip: "冰场灯光超有感觉！动起来抓拍，活力十足～",
    category: "运动健身",
    version: 1,
  },
  {
    id: "template_366",
    name: "房车公路",
    description: "房车旁公路旅行场景",
    overlayUrl: genSVG(366),
    thumbnail: genSVG(366),
    voiceTip: "房车公路超有旅行感！靠在车旁，看向远方～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_367",
    name: "天文台观星",
    description: "天文台或山顶星空观测",
    overlayUrl: genSVG(367),
    thumbnail: genSVG(367),
    voiceTip: "星空下超浪漫！仰头看天空，表情自然超有感觉～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_368",
    name: "古镇小巷",
    description: "江南古镇青石板小巷背景",
    overlayUrl: genSVG(368),
    thumbnail: genSVG(368),
    voiceTip: "古镇小巷超有年代感！靠墙站着，光影斑驳～",
    category: "人文风景",
    version: 1,
  },
  {
    id: "template_369",
    name: "码头灯塔",
    description: "海边码头灯塔和船舶背景",
    overlayUrl: genSVG(369),
    thumbnail: genSVG(369),
    voiceTip: "码头灯塔超有画面感！侧身站着让光线打在侧脸上～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_370",
    name: "天际线夜",
    description: "高楼天际线夜景背景",
    overlayUrl: genSVG(370),
    thumbnail: genSVG(370),
    voiceTip: "城市天际线夜景璀璨！打开闪光灯补补光～",
    category: "夜景",
    version: 1,
  },
  {
    id: "template_371",
    name: "樱花电车",
    description: "粉色樱花电车经过的瞬间",
    overlayUrl: genSVG(371),
    thumbnail: genSVG(371),
    voiceTip: "樱花电车超浪漫！站在电车旁，让花瓣飘落～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_372",
    name: "薰衣草田",
    description: "普罗旺斯薰衣草花田背景",
    overlayUrl: genSVG(372),
    thumbnail: genSVG(372),
    voiceTip: "薰衣草田紫色超梦幻！蹲下来让花做前景～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_373",
    name: "沙漠绿洲",
    description: "沙漠中绿洲棕榈树背景",
    overlayUrl: genSVG(373),
    thumbnail: genSVG(373),
    voiceTip: "沙漠绿洲超有异域感！光影对比强烈，侧身拍～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_374",
    name: "竹林小径",
    description: "静谧翠绿竹林小道背景",
    overlayUrl: genSVG(374),
    thumbnail: genSVG(374),
    voiceTip: "竹林小径超有禅意！阳光穿过竹叶光影斑驳～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_375",
    name: "瀑布飞泉",
    description: "瀑布前水雾弥漫场景",
    overlayUrl: genSVG(375),
    thumbnail: genSVG(375),
    voiceTip: "瀑布前水汽缭绕！侧身站着，光线柔和～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_376",
    name: "草原策马",
    description: "大草原骑马或马场场景",
    overlayUrl: genSVG(376),
    thumbnail: genSVG(376),
    voiceTip: "骑马姿势超有气场！挺直腰背，眼神看向远方～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_377",
    name: "热气球",
    description: "热气球升空俯瞰大地场景",
    overlayUrl: genSVG(377),
    thumbnail: genSVG(377),
    voiceTip: "热气球上俯瞰大地超震撼！张开双臂，感受飞翔～",
    category: "户外风景",
    version: 1,
  },
  {
    id: "template_378",
    name: "火车车窗",
    description: "火车旅行车窗风景同框",
    overlayUrl: genSVG(378),
    thumbnail: genSVG(378),
    voiceTip: "火车车窗超有旅途感！侧头看窗外，文艺感拉满～",
    category: "人文风景",
    version: 1,
  },
  {
    id: "template_379",
    name: "美术馆咖啡",
    description: "美术馆附属咖啡厅背景",
    overlayUrl: genSVG(379),
    thumbnail: genSVG(379),
    voiceTip: "美术馆咖啡厅超有文艺感！捧着咖啡，笑着看镜头～",
    category: "室内日常",
    version: 1,
  },
  {
    id: "template_380",
    name: "酒吧露台",
    description: "酒吧天台露台夜景背景",
    overlayUrl: genSVG(380),
    thumbnail: genSVG(380),
    voiceTip: "酒吧露台夜景超有氛围！靠着栏杆，笑一个～",
    category: "夜景",
    version: 1,
  },
  {
    id: "template_381",
    name: "圣诞市集",
    description: "圣诞市场小木屋彩灯背景",
    overlayUrl: genSVG(381),
    thumbnail: genSVG(381),
    voiceTip: "圣诞市集灯光超温暖！捧着热红酒，笑得灿烂～",
    category: "节日限定",
    version: 1,
  },
  {
    id: "template_382",
    name: "新年倒数",
    description: "新年倒数烟花和气球背景",
    overlayUrl: genSVG(382),
    thumbnail: genSVG(382),
    voiceTip: "新年倒计时超有仪式感！笑容灿烂迎接新一年～",
    category: "节日限定",
    version: 1,
  },
  {
    id: "template_383",
    name: "元宵灯会",
    description: "元宵节花灯夜景背景",
    overlayUrl: genSVG(383),
    thumbnail: genSVG(383),
    voiceTip: "元宵灯会超有传统美！站在灯笼旁，笑容温暖～",
    category: "节日限定",
    version: 1,
  },
  {
    id: "template_384",
    name: "音乐喷泉",
    description: "音乐喷泉灯光秀背景",
    overlayUrl: genSVG(384),
    thumbnail: genSVG(384),
    voiceTip: "音乐喷泉灯光璀璨！侧身站着，水光打在脸上～",
    category: "夜景",
    version: 1,
  },
  {
    id: "template_385",
    name: "夜幕摩天轮",
    description: "夜间摩天轮霓虹灯光背景",
    overlayUrl: genSVG(385),
    thumbnail: genSVG(385),
    voiceTip: "夜晚摩天轮灯光超浪漫！靠在窗边，看向城市夜景～",
    category: "夜景",
    version: 1,
  },
];

// ========== Round 5: 搜索索引 ==========
// 构建搜索索引（预计算关键词，提升搜索性能）
const SEARCH_INDEX = ALL_TEMPLATES.map(t => ({
  id: t.id,
  name: t.name || '',
  namePY: pinyinize(t.name || ''),
  description: t.description,
  voiceTip: t.voiceTip,
  category: t.category,
  // 难度标签（根据 voiceTip 长度和 category 推断）
  difficulty: inferDifficulty(t),
}))
function pinyinize(str) {
  // 简化的拼音索引（首字母）
  const map = { '侧': 'c', '撩': 'l', '托': 't', '回': 'h', '咖': 'k', '书': 's', '沙': 's', '海': 'h', '樱': 'y', '街': 'j', '天': 't', '下': 'x', '午': 'w', '火': 'h', '复': 'f', '运': 'y', '夜': 'y', '雨': 'y', '牵': 'q', '甜': 't', '对': 'd', '背': 'b', '生': 's', '毕': 'b', '旅': 'l', '宠': 'c', '摩': 'm', '浴': 'y', '星': 'x', '公': 'g', '泳': 'y', '古': 'g', '音': 'y', '露': 'l', '旋': 'x', '超市': 'c', '校园': 'x', '温': 'w', '旋': 'x', '植': 'z', '演': 'y', '酒': 'j', '阳': 'y', '居': 'j', '咖': 'k' }
  let result = ''
  for (const ch of str) {
    result += (map[ch] || ch[0] || '').toLowerCase()
  }
  return result
}
function inferDifficulty(t) {
  const tips = (t.voiceTip || '').length
  const cat = t.category || ''
  if (tips > 30) return 'hard'
  if (tips > 20 || cat === '情侣合照') return 'medium'
  return 'easy'
}
/** 简单中文分词搜索 */
function fuzzySearch(templates, query) {
  if (!query || query.trim().length < 1) return templates
  const q = query.trim().toLowerCase()
  // 分词（简单按字符）
  const keywords = q.split('').filter(c => c.trim())
  return templates.filter(t => {
    const searchable = `${t.name}${t.description}${t.voiceTip}${t.category}`.toLowerCase()
    return keywords.some(kw => searchable.includes(kw))
  })
}
exports.main = async (event = {}, context = {}) => {
  const localVersion = event.localVersion || 0
  const search = (event.search || '').trim()
  const category = event.category || ''
  const difficulty = event.difficulty || ''
  let templates = ALL_TEMPLATES
  // 分类筛选
  if (category && category !== '全部') {
    templates = templates.filter(t => t.category === category)
  }
  // 难度筛选
  if (difficulty) {
    const diffMap = { easy: 'easy', medium: 'medium', hard: 'hard' }
    const diff = diffMap[difficulty]
    if (diff) {
      templates = templates.filter(t => {
        const ti = SEARCH_INDEX.find(x => x.id === t.id)
        return ti && ti.difficulty === diff
      })
    }
  }
  // 搜索
  if (search) {
    templates = fuzzySearch(templates, search)
  }
  const update = ALL_TEMPLATES.filter(t => t.version > localVersion)
  const CATEGORIES = ["室内日常", "室内场景", "户外风景", "城市街拍", "餐厅美食", "情侣合照", "特殊风格"]
  const categoryCount = CATEGORIES.reduce((acc, cat) => {
    acc[cat] = ALL_TEMPLATES.filter(t => t.category === cat).length
    return acc
  }, {})
  return {
    latestVersion: CURRENT_VERSION,
    templates, // 搜索/筛选结果
    update, // 版本更新列表
    totalCount: ALL_TEMPLATES.length,
    categories: CATEGORIES,
    categoryCount,
    // 搜索索引元信息（用于调试/客户端缓存）
    meta: {
      version: CURRENT_VERSION,
      searchEnabled: true,
      categories: CATEGORIES,
      categoryCount,
    },
  }
}