/**
 * defaultTemplates.ts - 内置默认模板
 * 当云函数不可用时，作为离线 fallback
 * 包含 8 个最常用模板，覆盖主要场景
 */
import type { PoseTemplate } from '../components/camera/PoseTemplateOverlay'

// 预编码的 SVG 剪影（base64 编码，避免运行时 base64 计算）
const SVG_HAND_RAISE = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48cGF0aCBkPSJNIDc0IDgwIFEgNjUgMTE1IDcwIDE3MCBMIDg1IDI4MCIvPjxwYXRoIGQ9Ik0gMTI2IDgwIFEgMTM1IDExNSAxMzAgMTcwIEwgMTE1IDI4MCIvPgo8L3N2Zz4='
const SVG_HAIR_TOSS = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48cGF0aCBkPSJNIDc0IDgwIFEgNjUgMTE1IDcwIDE3MCBMIDg1IDI4MCIvPjxwYXRoIGQ9Ik0gMTI2IDgwIFEgMTM1IDExNSAxMzAgMTcwIEwgMTE1IDI4MCIvPjxwYXRoIGQ9Ik0gNzQgODggUSA0MCAxMDAgMzUgMTUwIFEgNDUgMTQ1IDU1IDE1NSIvPjxwYXRoIGQ9Ik0gMTI2IDg4IFEgMTU1IDk1IDE2NSAxMTUiLz48cGF0aCBkPSJNIDcwIDE3MCBRIDYwIDIxMCA1NSAyODAiLz48cGF0aCBkPSJNIDEzMCAxNzAgUSAxNDAgMjEwIDE0NSAyODAiLz48cGF0aCBkPSJNIDM1IDE1MCBRIDI1IDE3MCAyMCAxOTAiIGZpbGw9Im5vbmUiIHN0cm9rZS1kYXNoYXJyYXk9IjMsMiIvPgo8L3N2Zz4='
const SVG_CHIN_REST = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48ZWxsaXBzZSBjeD0iMTIwIiBjeT0iNjUiIHJ4PSIxMCIgcnk9IjgiIGZpbGw9InJnYmEoMjU1LDEwNywxMDcsMC41KSIgc3Ryb2tlPSJub25lIi8+PHBhdGggZD0iTSA3NCA4MCBRIDY1IDExNSA2OCAxNjUgTCA4MCAyODAiLz48cGF0aCBkPSJNIDEyNiA4MCBRIDEzOCAxMTUgMTMyIDE2NSBMIDEyMCAyODAiLz48cGF0aCBkPSJNIDc0IDkwIFEgNTUgMTAwIDQ1IDEzMCIvPjxwYXRoIGQ9Ik0gMTI2IDk1IFEgMTUwIDEwMCAxNjUgOTAiLz48cGF0aCBkPSJNIDY4IDE2NSBRIDU4IDIwNSA1NSAyODAiLz48cGF0aCBkPSJNIDEzMiAxNjUgUSAxNDIgMjA1IDE0NSAyODAiLz4KPC9zdmc+'
const SVG_BACK_TURN = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48cGF0aCBkPSJNIDcwIDgyIFEgNjAgMTIwIDY1IDE4MCBMIDgyIDI4MCIvPjxwYXRoIGQ9Ik0gMTMwIDgyIFEgMTQwIDEyMCAxMzUgMTgwIEwgMTE4IDI4MCIvPjxwYXRoIGQ9Ik0gNzAgOTAgUSAyMCAxMDAgMTUgMTUwIiBmaWxsPSJub25lIi8+PHBhdGggZD0iTSAxMzAgOTAgUSAxODAgMTAwIDE4NSAxNTAiIGZpbGw9Im5vbmUiLz48cGF0aCBkPSJNIDE1IDE1MCBRIDEwIDE4MCAxNSAyMjAiIGZpbGw9Im5vbmUiLz48cGF0aCBkPSJNIDY1IDE4MCBRIDU1IDIyMCA1MCAyODAiLz48cGF0aCBkPSJNIDEzNSAxODAgUSAxNDUgMjIwIDE1MCAyODAiLz4KPC9zdmc+'
const SVG_RUNNING = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI0OCIgcng9IjI1IiByeT0iMjgiLz48cGF0aCBkPSJNIDc4IDc2IFEgNzAgMTA1IDcyIDE0NSBMIDg1IDE5MCIvPjxwYXRoIGQ9Ik0gMTIyIDc2IFEgMTMwIDEwNSAxMjggMTQ1IEwgMTE4IDE5MCIvPjxwYXRoIGQ9Ik0gNzIgMTQ1IFEgNDAgMTQwIDEwIDE2NSIvPjxwYXRoIGQ9Ik0gMTI4IDE0NSBRIDE2MCAxMzUgMTk1IDE1NSIvPjxwYXRoIGQ9Ik0gODUgMTkwIFEgNzAgMjMwIDU1IDI4MCIvPjxwYXRoIGQ9Ik0gMTE4IDE5MCBRIDEzMCAyMzAgMTQ1IDI4MCIvPjxwYXRoIGQ9Ik0gNTUgMjgwIFEgNDUgMjk1IDMwIDMwMCIvPjxwYXRoIGQ9Ik0gMTQ1IDI4MCBRIDE1NSAyOTUgMTcwIDMwMCIvPgo8L3N2Zz4='
const SVG_SAKURA = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48cGF0aCBkPSJNIDc0IDgwIFEgNjUgMTE1IDY4IDE2MCBMIDgyIDI4MCIvPjxwYXRoIGQ9Ik0gMTI2IDgwIFEgMTM4IDExNSAxMzIgMTYwIEwgMTIwIDI4MCIvPjxjaXJjbGUgY3g9IjMwIiBjeT0iNDAiIHI9IjUiIGZpbGw9InJnYmEoMjU1LDE4MiwxOTMsMC42KSIgc3Ryb2tlPSJub25lIi8+PGNpcmNsZSBjeD0iNTUiIGN5PSIzMCIgcj0iNCIgZmlsbD0icmdiYSgyNTUsMTgyLDE5MywwLjYpIiBzdHJva2U9Im5vbmUiLz48Y2lyY2xlIGN4PSIxNzAiIGN5PSIzOCIgcj0iNSIgZmlsbD0icmdiYSgyNTUsMTgyLDE5MywwLjYpIiBzdHJva2U9Im5vbmUiLz48Y2lyY2xlIGN4PSIxNDUiIGN5PSIyOCIgcj0iNCIgZmlsbD0icmdiYSgyNTUsMTgyLDE5MywwLjYpIiBzdHJva2U9Im5vbmUiLz4KPC9zdmc+'
const SVG_COFFEE = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSIxMDAiIGN5PSI1MCIgcng9IjI4IiByeT0iMzIiLz48cGF0aCBkPSJNIDc0IDgwIFEgNjUgMTE1IDY4IDE2MCBMIDgyIDI4MCIvPjxwYXRoIGQ9Ik0gMTI2IDgwIFEgMTM4IDExNSAxMzIgMTYwIEwgMTIwIDI4MCIvPjxwYXRoIGQ9Ik0gNzQgOTAgUSA1MCA5NSAzNSAxMTAiLz48cGF0aCBkPSJNIDM1IDExMCBRIDIwIDEyMCAxNSAxNDAgVCA0MCAxNDAgUSA0NSAxMjUgNTAgMTE1Ii8+PHBhdGggZD0iTSAxMjYgOTAgUSAxNTUgMTAwIDE2NSAxMTUiLz48ZWxsaXBzZSBjeD0iMzAiIGN5PSIxMzAiIHJ4PSI4IiByeT0iNCIgZmlsbD0icmdiYSgyNTUsMTA3LDEwNywwLjQpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC41KSIgc3Ryb2tlLXdpZHRoPSIxIi8+Cjwvc3ZnPg=='
const SVG_HOLDING_HANDS = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMDAgMzAwIiBmaWxsPSJyZ2JhKDI1NSwxMDcsMTA3LDAuMzUpIiBzdHJva2U9InJnYmEoMjU1LDI1NSwyNTUsMC42KSIgc3Ryb2tlLXdpZHRoPSIxLjUiPjxlbGxpcHNlIGN4PSI2MCIgY3k9IjUwIiByeD0iMjgiIHJ5PSIzMiIvPjxwYXRoIGQ9Ik0gNjAgODIgUSA1MCAxMjAgNTUgMTgwIEwgNDAgMjgwIi8+PHBhdGggZD0iTSA5MCA4MiBRIDgwIDEyMCA4NSAxODAgTCAxMjAgMjgwIi8+PHBhdGggZD0iTSAxMzAgODIgUSAxNDAgMTIwIDEzNSAxODAgTCAxNDAgMjgwIi8+PHBhdGggZD0iTSAxNTAgODIgUSAxNjAgMTIwIDE2NSAxODAgTCAxNjAgMjgwIi8+PHBhdGggZD0iTSAzMCA5MCBRIDIwIDExMCAxNSAxNTAiIGZpbGw9Im5vbmUiLz48cGF0aCBkPSJNIDkwIDkwIFEgMTQwIDEwMCAxNTAgMTUwIiBmaWxsPSJub25lIi8+PHBhdGggZD0iTSAyNSAxODAgUSAxNSAyMjAgMTAgMjgwIi8+PHBhdGggZD0iTSA4NSAxODAgUSAxMDAgMjIwIDExMCAyODAiLz48cGF0aCBkPSJNIDEzNSAxODAgUSAxNDUgMjIwIDE1MCAyODAiLz48cGF0aCBkPSJNIDE2NSAxODAgUSAxNzUgMjIwIDE4MCAyODAiLz4KPC9zdmc+'

export const DEFAULT_TEMPLATES: PoseTemplate[] = [
  {
    id: 'local_001', name: '侧身回眸',
    description: '微微侧身，回头看镜头，自然又显瘦',
    overlayUrl: SVG_HAND_RAISE, thumbnail: SVG_HAND_RAISE,
    voiceTip: '侧身站好，轻轻回头看我，笑一个～',
    category: '室内日常', version: 1,
  },
  {
    id: 'local_002', name: '撩发pose',
    description: '一只手轻轻撩起头发，优雅又灵动',
    overlayUrl: SVG_HAIR_TOSS, thumbnail: SVG_HAIR_TOSS,
    voiceTip: '单手轻轻撩一下耳边头发，下巴微微抬起',
    category: '室内日常', version: 1,
  },
  {
    id: 'local_003', name: '托腮文艺',
    description: '托腮思考，文艺感十足，适合近景特写',
    overlayUrl: SVG_CHIN_REST, thumbnail: SVG_CHIN_REST,
    voiceTip: '用手托住一边脸，眼睛看我，眼神温柔一点',
    category: '室内日常', version: 1,
  },
  {
    id: 'local_004', name: '背影回眸',
    description: '先拍背影，再慢慢转身抓拍，自然又有故事感',
    overlayUrl: SVG_BACK_TURN, thumbnail: SVG_BACK_TURN,
    voiceTip: '先背对我，然后慢慢转身，回头那一瞬间按下快门！',
    category: '室内日常', version: 1,
  },
  {
    id: 'local_005', name: '海边奔跑',
    description: '海边跑起来抓拍，动感十足超出片',
    overlayUrl: SVG_RUNNING, thumbnail: SVG_RUNNING,
    voiceTip: '在海边慢慢跑起来，裙摆飞扬的瞬间抓拍！',
    category: '户外风景', version: 1,
  },
  {
    id: 'local_006', name: '樱花树下',
    description: '樱花飘落，浪漫满分的春日人像',
    overlayUrl: SVG_SAKURA, thumbnail: SVG_SAKURA,
    voiceTip: '站在樱花树下，抬头看花，让花瓣落在头发上～',
    category: '户外风景', version: 1,
  },
  {
    id: 'local_007', name: '咖啡杯时光',
    description: '手托咖啡杯，文艺小资感溢出屏幕',
    overlayUrl: SVG_COFFEE, thumbnail: SVG_COFFEE,
    voiceTip: '双手捧杯，眼睛看镜头，嘴角微微上扬～',
    category: '室内日常', version: 1,
  },
  {
    id: 'local_008', name: '牵手背影',
    description: '两人牵手背对镜头，温馨又有意境',
    overlayUrl: SVG_HOLDING_HANDS, thumbnail: SVG_HOLDING_HANDS,
    voiceTip: '两个人背对镜头站好，手牵手，等我倒数三二一！',
    category: '情侣合照', version: 1,
  },
]
